/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;

/**
 *
 * @author Hp
 */
public class MisViajes extends javax.swing.JFrame {

    /**
     * Creates new form MisViajes
     */
    public MisViajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelLateral = new javax.swing.JPanel();
        ImagenLogo = new javax.swing.JLabel();
        BotonHoteles = new javax.swing.JButton();
        BotonMisViajes = new javax.swing.JButton();
        BotonVuelos = new javax.swing.JButton();
        BotonCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelContenido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelCarta2 = new javax.swing.JPanel();
        ImagenMadrid = new javax.swing.JLabel();
        TituloMadrid = new javax.swing.JLabel();
        DescripcionMadrid = new javax.swing.JLabel();
        Corazon3 = new javax.swing.JLabel();
        PanelBarcelona = new javax.swing.JPanel();
        ImagenBarcelona = new javax.swing.JLabel();
        TituloBarcelona = new javax.swing.JLabel();
        DescripcionBarcelona = new javax.swing.JLabel();
        Corazon4 = new javax.swing.JLabel();
        PanelMalaga = new javax.swing.JPanel();
        ImagenMalaga = new javax.swing.JLabel();
        TituloMalaga = new javax.swing.JLabel();
        DescripcionMalaga = new javax.swing.JLabel();
        Corazon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setBackground(new java.awt.Color(255, 51, 51));
        PanelPrincipal.setMaximumSize(new java.awt.Dimension(1200, 700));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLateral.setBackground(new java.awt.Color(255, 255, 255));
        PanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AvionLogo.png"))); // NOI18N
        PanelLateral.add(ImagenLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 115, -1, -1));

        BotonHoteles.setBackground(new java.awt.Color(9, 157, 221));
        BotonHoteles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonHoteles.setForeground(new java.awt.Color(255, 255, 255));
        BotonHoteles.setText("Hoteles");
        BotonHoteles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonHotelesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHotelesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHotelesMouseExited(evt);
            }
        });
        PanelLateral.add(BotonHoteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 434, 203, 72));

        BotonMisViajes.setBackground(new java.awt.Color(7, 109, 154));
        BotonMisViajes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonMisViajes.setForeground(new java.awt.Color(255, 255, 255));
        BotonMisViajes.setText("Mis Viajes");
        PanelLateral.add(BotonMisViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 526, 203, 72));

        BotonVuelos.setBackground(new java.awt.Color(9, 157, 221));
        BotonVuelos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonVuelos.setForeground(new java.awt.Color(255, 255, 255));
        BotonVuelos.setText("Vuelos");
        BotonVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVuelosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonVuelosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonVuelosMouseExited(evt);
            }
        });
        PanelLateral.add(BotonVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 344, 203, 72));

        BotonCerrar.setBackground(new java.awt.Color(9, 157, 221));
        BotonCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setText("Cerrar");
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseExited(evt);
            }
        });
        PanelLateral.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 616, 203, 72));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bienvenido a Telena");
        PanelLateral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        PanelPrincipal.add(PanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        PanelContenido.setBackground(new java.awt.Color(56, 109, 189));
        PanelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mis Viajes");
        PanelContenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        PanelCarta2.setBackground(new java.awt.Color(255, 255, 255));
        PanelCarta2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelCarta2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelCarta2MouseExited(evt);
            }
        });
        PanelCarta2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenMadrid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Madrid.png"))); // NOI18N
        PanelCarta2.add(ImagenMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TituloMadrid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloMadrid.setForeground(new java.awt.Color(9, 157, 221));
        TituloMadrid.setText("Madrid");
        PanelCarta2.add(TituloMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        DescripcionMadrid.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescripcionMadrid.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid.setText("<html>Madrid es un municipio y una ciudad de España. La localidad, con categoría <br> histórica de villa, ​es la capital del Estado​ y de la Comunidad de Madrid.<br>\nCapital de España y conocida habitualmente como Villa y Corte,<br> Madrid es la mayor ciudad del país y la segunda de la Unión Europea,<br> con una población de más de <br>3 millones de habitantes (más de 6 en el área metropolitana).");
        PanelCarta2.add(DescripcionMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 120));

        Corazon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png"))); // NOI18N
        Corazon3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Corazon3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Corazon3MouseExited(evt);
            }
        });
        PanelCarta2.add(Corazon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        PanelContenido.add(PanelCarta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 740, 190));

        PanelBarcelona.setBackground(new java.awt.Color(255, 255, 255));
        PanelBarcelona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelBarcelonaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelBarcelonaMouseExited(evt);
            }
        });
        PanelBarcelona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenBarcelona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barcelona.png"))); // NOI18N
        PanelBarcelona.add(ImagenBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TituloBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloBarcelona.setForeground(new java.awt.Color(9, 157, 221));
        TituloBarcelona.setText("Barcelona");
        PanelBarcelona.add(TituloBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        DescripcionBarcelona.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionBarcelona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescripcionBarcelona.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionBarcelona.setText("<html>Barcelona, la capital cosmopolita de la región de Cataluña en España,<br> es conocida por su arte y arquitectura. La fantástica iglesia de la Sagrada Familia<br> y otros hitos modernistas diseñados por Antoni Gaudí adornan la ciudad.<br> El Museo Picasso y la Fundación Joan Miró muestran el arte moderno de los artistas<br> que dan origen a sus nombres. ");
        PanelBarcelona.add(DescripcionBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 100));

        Corazon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png"))); // NOI18N
        Corazon4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Corazon4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Corazon4MouseExited(evt);
            }
        });
        PanelBarcelona.add(Corazon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        PanelContenido.add(PanelBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 740, 190));

        PanelMalaga.setBackground(new java.awt.Color(255, 255, 255));
        PanelMalaga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMalagaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMalagaMouseExited(evt);
            }
        });
        PanelMalaga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenMalaga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Malaga.png"))); // NOI18N
        PanelMalaga.add(ImagenMalaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TituloMalaga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloMalaga.setForeground(new java.awt.Color(9, 157, 221));
        TituloMalaga.setText("Málaga");
        PanelMalaga.add(TituloMalaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        DescripcionMalaga.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionMalaga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescripcionMalaga.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMalaga.setText("<html>Málaga es una ciudad y municipio español, capital de la provincia homónima, <br>situada en la comunidad autónoma de Andalucía<br>\nMonumentos como la Alcazaba, el Castillo de Gibralfaro, el Teatro Romano <br>o el mercado de Atarazanas, nos trasladan a un fértil pasado. <br>\nNumerosos museos como el Picasso, el Thyssen o La Térmica, centro abierto a las <br>últimas tendencias del arte, muestran la efervescencia de <br>una ciudad que apuesta por la cultura.");
        PanelMalaga.add(DescripcionMalaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, 140));

        Corazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png"))); // NOI18N
        Corazon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CorazonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CorazonMouseExited(evt);
            }
        });
        PanelMalaga.add(Corazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, -1, -1));

        PanelContenido.add(PanelMalaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 740, 190));

        PanelPrincipal.add(PanelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 900, 700));

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CorazonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorazonMouseEntered
        Corazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazonazul.png")));
    }//GEN-LAST:event_CorazonMouseEntered

    private void CorazonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorazonMouseExited
        Corazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png")));
    }//GEN-LAST:event_CorazonMouseExited

    private void BotonVuelosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVuelosMouseEntered
        BotonVuelos.setBackground(new Color(7,109,154));
    }//GEN-LAST:event_BotonVuelosMouseEntered

    private void BotonVuelosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVuelosMouseExited
        BotonVuelos.setBackground(new Color(9,157,221));
            }//GEN-LAST:event_BotonVuelosMouseExited

    private void Corazon3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon3MouseEntered
        Corazon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazonazul.png")));
    }//GEN-LAST:event_Corazon3MouseEntered

    private void Corazon3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon3MouseExited
        Corazon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png")));
    }//GEN-LAST:event_Corazon3MouseExited

    private void Corazon4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon4MouseEntered
       Corazon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazonazul.png")));
    }//GEN-LAST:event_Corazon4MouseEntered

    private void Corazon4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon4MouseExited
       Corazon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png")));
    }//GEN-LAST:event_Corazon4MouseExited

    private void BotonHotelesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHotelesMouseEntered
        BotonHoteles.setBackground(new Color(7,109,154));
    }//GEN-LAST:event_BotonHotelesMouseEntered

    private void BotonHotelesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHotelesMouseExited
        BotonHoteles.setBackground(new Color(9,157,221));
    }//GEN-LAST:event_BotonHotelesMouseExited

    private void BotonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseEntered
        BotonCerrar.setBackground(new Color(7,109,154));
    }//GEN-LAST:event_BotonCerrarMouseEntered

    private void BotonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseExited
        BotonCerrar.setBackground(new Color(9,157,221));
    }//GEN-LAST:event_BotonCerrarMouseExited

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void PanelMalagaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalagaMouseEntered
        PanelMalaga.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_PanelMalagaMouseEntered

    private void PanelMalagaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalagaMouseExited
        PanelMalaga.setBackground(new Color(255,255,255 ));

    }//GEN-LAST:event_PanelMalagaMouseExited

    private void PanelCarta2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCarta2MouseEntered
        PanelCarta2.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_PanelCarta2MouseEntered

    private void PanelCarta2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelCarta2MouseExited
        PanelCarta2.setBackground(new Color(255,255,255 ));
    }//GEN-LAST:event_PanelCarta2MouseExited

    private void PanelBarcelonaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarcelonaMouseEntered
        PanelBarcelona.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_PanelBarcelonaMouseEntered

    private void PanelBarcelonaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelBarcelonaMouseExited
        PanelBarcelona.setBackground(new Color(255,255,255 ));
    }//GEN-LAST:event_PanelBarcelonaMouseExited

    private void BotonVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVuelosMouseClicked
        Vuelos abrir = new Vuelos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);      }//GEN-LAST:event_BotonVuelosMouseClicked

    private void BotonHotelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHotelesMouseClicked
Hoteles abrir = new Hoteles();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_BotonHotelesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisViajes().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JButton BotonHoteles;
    private javax.swing.JButton BotonMisViajes;
    private javax.swing.JButton BotonVuelos;
    private javax.swing.JLabel Corazon;
    private javax.swing.JLabel Corazon3;
    private javax.swing.JLabel Corazon4;
    private javax.swing.JLabel DescripcionBarcelona;
    private javax.swing.JLabel DescripcionMadrid;
    private javax.swing.JLabel DescripcionMalaga;
    private javax.swing.JLabel ImagenBarcelona;
    private javax.swing.JLabel ImagenLogo;
    private javax.swing.JLabel ImagenMadrid;
    private javax.swing.JLabel ImagenMalaga;
    private javax.swing.JPanel PanelBarcelona;
    private javax.swing.JPanel PanelCarta2;
    private javax.swing.JPanel PanelContenido;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JPanel PanelMalaga;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel TituloBarcelona;
    private javax.swing.JLabel TituloMadrid;
    private javax.swing.JLabel TituloMalaga;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
