/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Hp
 */
public class Vuelos extends javax.swing.JFrame {

    /**
     * Creates new form MisViajes
     */
    public Vuelos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelLateral = new javax.swing.JPanel();
        ImagenLogo = new javax.swing.JLabel();
        BotonHoteles = new javax.swing.JButton();
        BotonMisViajes = new javax.swing.JButton();
        BotonVuelos = new javax.swing.JButton();
        BotonCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PanelContenido = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        PanelMalaga = new javax.swing.JPanel();
        ImagenMalaga = new javax.swing.JLabel();
        TituloMalaga = new javax.swing.JLabel();
        DescripcionMadrid6 = new javax.swing.JLabel();
        PanelMalaga1 = new javax.swing.JPanel();
        ImagenMalaga1 = new javax.swing.JLabel();
        TituloMalaga1 = new javax.swing.JLabel();
        DescripcionMadrid2 = new javax.swing.JLabel();
        Corazon = new javax.swing.JLabel();
        PanelMalaga2 = new javax.swing.JPanel();
        ImagenMalaga2 = new javax.swing.JLabel();
        TituloMalaga2 = new javax.swing.JLabel();
        Corazon5 = new javax.swing.JLabel();
        DescripcionMadrid9 = new javax.swing.JLabel();
        PanelMalaga3 = new javax.swing.JPanel();
        ImagenMalaga3 = new javax.swing.JLabel();
        TituloMalaga3 = new javax.swing.JLabel();
        Corazon6 = new javax.swing.JLabel();
        DescripcionMadrid8 = new javax.swing.JLabel();
        PanelMalaga4 = new javax.swing.JPanel();
        ImagenMalaga4 = new javax.swing.JLabel();
        TituloMalaga4 = new javax.swing.JLabel();
        Corazon8 = new javax.swing.JLabel();
        DescripcionMadrid10 = new javax.swing.JLabel();
        PanelMalaga6 = new javax.swing.JPanel();
        ImagenMalaga6 = new javax.swing.JLabel();
        TituloMalaga6 = new javax.swing.JLabel();
        Corazon1 = new javax.swing.JLabel();
        DescripcionMadrid11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPrincipal.setBackground(new java.awt.Color(255, 51, 51));
        PanelPrincipal.setMaximumSize(new java.awt.Dimension(1200, 700));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelLateral.setBackground(new java.awt.Color(255, 255, 255));
        PanelLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AvionLogo.png"))); // NOI18N
        PanelLateral.add(ImagenLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 115, -1, -1));

        BotonHoteles.setBackground(new java.awt.Color(9, 157, 221));
        BotonHoteles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonHoteles.setForeground(new java.awt.Color(255, 255, 255));
        BotonHoteles.setText("Hoteles");
        BotonHoteles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonHotelesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonHotelesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonHotelesMouseExited(evt);
            }
        });
        PanelLateral.add(BotonHoteles, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 434, 203, 72));

        BotonMisViajes.setBackground(new java.awt.Color(9, 157, 221));
        BotonMisViajes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonMisViajes.setForeground(new java.awt.Color(255, 255, 255));
        BotonMisViajes.setText("Mis Viajes");
        BotonMisViajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMisViajesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMisViajesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMisViajesMouseExited(evt);
            }
        });
        PanelLateral.add(BotonMisViajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 526, 203, 72));

        BotonVuelos.setBackground(new java.awt.Color(7, 109, 154));
        BotonVuelos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonVuelos.setForeground(new java.awt.Color(255, 255, 255));
        BotonVuelos.setText("Vuelos");
        PanelLateral.add(BotonVuelos, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 344, 203, 72));

        BotonCerrar.setBackground(new java.awt.Color(9, 157, 221));
        BotonCerrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        BotonCerrar.setText("Cerrar");
        BotonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonCerrarMouseExited(evt);
            }
        });
        PanelLateral.add(BotonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 616, 203, 72));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bienvenido a Telena");
        PanelLateral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, -1, -1));

        PanelPrincipal.add(PanelLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 700));

        PanelContenido.setBackground(new java.awt.Color(56, 109, 189));
        PanelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Los Vuelos Más Populares");
        PanelContenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        PanelMalaga.setBackground(new java.awt.Color(255, 255, 255));
        PanelMalaga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMalagaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMalagaMouseExited(evt);
            }
        });
        PanelMalaga.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenMalaga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Barcelona.png"))); // NOI18N
        PanelMalaga.add(ImagenMalaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TituloMalaga.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloMalaga.setForeground(new java.awt.Color(9, 157, 221));
        TituloMalaga.setText("Barcelona");
        PanelMalaga.add(TituloMalaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        DescripcionMadrid6.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescripcionMadrid6.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid6.setText("<html> Vuelos•Hoteles•Alquiler de coches");
        DescripcionMadrid6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DescripcionMadrid6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DescripcionMadrid6MouseExited(evt);
            }
        });
        PanelMalaga.add(DescripcionMadrid6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, -1));

        PanelContenido.add(PanelMalaga, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 370, 190));

        PanelMalaga1.setBackground(new java.awt.Color(255, 255, 255));
        PanelMalaga1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMalaga1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMalaga1MouseExited(evt);
            }
        });
        PanelMalaga1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenMalaga1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Malaga.png"))); // NOI18N
        PanelMalaga1.add(ImagenMalaga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TituloMalaga1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloMalaga1.setForeground(new java.awt.Color(9, 157, 221));
        TituloMalaga1.setText("Málaga");
        PanelMalaga1.add(TituloMalaga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        DescripcionMadrid2.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescripcionMadrid2.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid2.setText("<html> Vuelos•Hoteles•Alquiler de coches");
        DescripcionMadrid2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DescripcionMadrid2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DescripcionMadrid2MouseExited(evt);
            }
        });
        PanelMalaga1.add(DescripcionMadrid2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, -1));

        Corazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png"))); // NOI18N
        Corazon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CorazonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CorazonMouseExited(evt);
            }
        });
        PanelMalaga1.add(Corazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, -1));

        PanelContenido.add(PanelMalaga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 370, 190));

        PanelMalaga2.setBackground(new java.awt.Color(255, 255, 255));
        PanelMalaga2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMalaga2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMalaga2MouseExited(evt);
            }
        });
        PanelMalaga2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenMalaga2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Valencia.png"))); // NOI18N
        PanelMalaga2.add(ImagenMalaga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TituloMalaga2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloMalaga2.setForeground(new java.awt.Color(9, 157, 221));
        TituloMalaga2.setText("Valencia");
        PanelMalaga2.add(TituloMalaga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        Corazon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png"))); // NOI18N
        Corazon5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Corazon5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Corazon5MouseExited(evt);
            }
        });
        PanelMalaga2.add(Corazon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, -1));

        DescripcionMadrid9.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescripcionMadrid9.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid9.setText("<html> Vuelos•Hoteles•Alquiler de coches");
        DescripcionMadrid9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DescripcionMadrid9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DescripcionMadrid9MouseExited(evt);
            }
        });
        PanelMalaga2.add(DescripcionMadrid9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, -1));

        PanelContenido.add(PanelMalaga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 370, 190));

        PanelMalaga3.setBackground(new java.awt.Color(255, 255, 255));
        PanelMalaga3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMalaga3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMalaga3MouseExited(evt);
            }
        });
        PanelMalaga3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenMalaga3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Paris.png"))); // NOI18N
        PanelMalaga3.add(ImagenMalaga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TituloMalaga3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloMalaga3.setForeground(new java.awt.Color(9, 157, 221));
        TituloMalaga3.setText("Paris");
        PanelMalaga3.add(TituloMalaga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        Corazon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png"))); // NOI18N
        Corazon6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Corazon6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Corazon6MouseExited(evt);
            }
        });
        PanelMalaga3.add(Corazon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, -1));

        DescripcionMadrid8.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescripcionMadrid8.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid8.setText("<html> Vuelos•Hoteles•Alquiler de coches");
        DescripcionMadrid8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DescripcionMadrid8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DescripcionMadrid8MouseExited(evt);
            }
        });
        PanelMalaga3.add(DescripcionMadrid8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, -1));

        PanelContenido.add(PanelMalaga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 370, 190));

        PanelMalaga4.setBackground(new java.awt.Color(255, 255, 255));
        PanelMalaga4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMalaga4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMalaga4MouseExited(evt);
            }
        });
        PanelMalaga4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenMalaga4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Roma.png"))); // NOI18N
        PanelMalaga4.add(ImagenMalaga4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TituloMalaga4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloMalaga4.setForeground(new java.awt.Color(9, 157, 221));
        TituloMalaga4.setText("Roma");
        PanelMalaga4.add(TituloMalaga4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        Corazon8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png"))); // NOI18N
        Corazon8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Corazon8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Corazon8MouseExited(evt);
            }
        });
        PanelMalaga4.add(Corazon8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, -1));

        DescripcionMadrid10.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescripcionMadrid10.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid10.setText("<html> Vuelos•Hoteles•Alquiler de coches");
        DescripcionMadrid10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DescripcionMadrid10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DescripcionMadrid10MouseExited(evt);
            }
        });
        PanelMalaga4.add(DescripcionMadrid10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, -1));

        PanelContenido.add(PanelMalaga4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 370, 190));

        PanelMalaga6.setBackground(new java.awt.Color(255, 255, 255));
        PanelMalaga6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelMalaga6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelMalaga6MouseExited(evt);
            }
        });
        PanelMalaga6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenMalaga6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Madrid.png"))); // NOI18N
        PanelMalaga6.add(ImagenMalaga6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TituloMalaga6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TituloMalaga6.setForeground(new java.awt.Color(9, 157, 221));
        TituloMalaga6.setText("Madrid");
        PanelMalaga6.add(TituloMalaga6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        Corazon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png"))); // NOI18N
        Corazon1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Corazon1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Corazon1MouseExited(evt);
            }
        });
        PanelMalaga6.add(Corazon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 30, -1));

        DescripcionMadrid11.setBackground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        DescripcionMadrid11.setForeground(new java.awt.Color(0, 0, 0));
        DescripcionMadrid11.setText("<html> Vuelos•Hoteles•Alquiler de coches");
        DescripcionMadrid11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DescripcionMadrid11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DescripcionMadrid11MouseExited(evt);
            }
        });
        PanelMalaga6.add(DescripcionMadrid11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 140, -1));

        PanelContenido.add(PanelMalaga6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 370, 190));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 56)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vuelos");
        PanelContenido.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, -1, -1));

        PanelPrincipal.add(PanelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 900, 700));

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonHotelesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHotelesMouseEntered
        BotonHoteles.setBackground(new Color(7,109,154));
    }//GEN-LAST:event_BotonHotelesMouseEntered

    private void BotonHotelesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHotelesMouseExited
        BotonHoteles.setBackground(new Color(9,157,221));
    }//GEN-LAST:event_BotonHotelesMouseExited

    private void BotonMisViajesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMisViajesMouseEntered
        BotonMisViajes.setBackground(new Color(7,109,154));
    }//GEN-LAST:event_BotonMisViajesMouseEntered

    private void BotonMisViajesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMisViajesMouseExited
        BotonMisViajes.setBackground(new Color(9,157,221));
    }//GEN-LAST:event_BotonMisViajesMouseExited

    private void BotonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseEntered
        BotonCerrar.setBackground(new Color(7,109,154));
    }//GEN-LAST:event_BotonCerrarMouseEntered

    private void BotonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseExited
        BotonCerrar.setBackground(new Color(9,157,221));
    }//GEN-LAST:event_BotonCerrarMouseExited

    private void BotonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_BotonCerrarMouseClicked

    private void PanelMalagaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalagaMouseEntered
    }//GEN-LAST:event_PanelMalagaMouseEntered

    private void PanelMalagaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalagaMouseExited

    }//GEN-LAST:event_PanelMalagaMouseExited

    private void PanelMalaga1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga1MouseEntered

    private void PanelMalaga1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga1MouseExited

    private void PanelMalaga2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga2MouseEntered

    private void PanelMalaga2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga2MouseExited

    private void PanelMalaga3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga3MouseEntered

    private void PanelMalaga3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga3MouseExited

    private void PanelMalaga4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga4MouseEntered

    private void PanelMalaga4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga4MouseExited

    private void PanelMalaga6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga6MouseEntered

    private void PanelMalaga6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMalaga6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_PanelMalaga6MouseExited

    private void BotonHotelesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonHotelesMouseClicked
        // TODO add your handling code here:
        Hoteles abrir = new Hoteles();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonHotelesMouseClicked

    private void BotonMisViajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMisViajesMouseClicked
        MisViajes abrir = new MisViajes();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_BotonMisViajesMouseClicked

    private void CorazonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorazonMouseEntered
        Corazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazonazul.png")));
    }//GEN-LAST:event_CorazonMouseEntered

    private void CorazonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorazonMouseExited
        Corazon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/corazon.png")));
    }//GEN-LAST:event_CorazonMouseExited

    private void Corazon1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Corazon1MouseEntered

    private void Corazon1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Corazon1MouseExited

    private void Corazon5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Corazon5MouseEntered

    private void Corazon5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Corazon5MouseExited

    private void Corazon6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Corazon6MouseEntered

    private void Corazon6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Corazon6MouseExited

    private void Corazon8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Corazon8MouseEntered

    private void Corazon8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Corazon8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Corazon8MouseExited

    private void DescripcionMadrid2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid2MouseEntered
        DescripcionMadrid2.setForeground(new Color(7,109,154));

    }//GEN-LAST:event_DescripcionMadrid2MouseEntered

    private void DescripcionMadrid2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid2MouseExited
        DescripcionMadrid2.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_DescripcionMadrid2MouseExited

    private void DescripcionMadrid6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid6MouseEntered

    private void DescripcionMadrid6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid6MouseExited

    private void DescripcionMadrid8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid8MouseEntered

    private void DescripcionMadrid8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid8MouseExited

    private void DescripcionMadrid9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid9MouseEntered

    private void DescripcionMadrid9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid9MouseExited

    private void DescripcionMadrid10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid10MouseEntered

    private void DescripcionMadrid10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid10MouseExited

    private void DescripcionMadrid11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid11MouseEntered

    private void DescripcionMadrid11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DescripcionMadrid11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_DescripcionMadrid11MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MisViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MisViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MisViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MisViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MisViajes().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonCerrar;
    private javax.swing.JButton BotonHoteles;
    private javax.swing.JButton BotonMisViajes;
    private javax.swing.JButton BotonVuelos;
    private javax.swing.JLabel Corazon;
    private javax.swing.JLabel Corazon1;
    private javax.swing.JLabel Corazon5;
    private javax.swing.JLabel Corazon6;
    private javax.swing.JLabel Corazon8;
    private javax.swing.JLabel DescripcionMadrid10;
    private javax.swing.JLabel DescripcionMadrid11;
    private javax.swing.JLabel DescripcionMadrid2;
    private javax.swing.JLabel DescripcionMadrid6;
    private javax.swing.JLabel DescripcionMadrid8;
    private javax.swing.JLabel DescripcionMadrid9;
    private javax.swing.JLabel ImagenLogo;
    private javax.swing.JLabel ImagenMalaga;
    private javax.swing.JLabel ImagenMalaga1;
    private javax.swing.JLabel ImagenMalaga2;
    private javax.swing.JLabel ImagenMalaga3;
    private javax.swing.JLabel ImagenMalaga4;
    private javax.swing.JLabel ImagenMalaga6;
    private javax.swing.JPanel PanelContenido;
    private javax.swing.JPanel PanelLateral;
    private javax.swing.JPanel PanelMalaga;
    private javax.swing.JPanel PanelMalaga1;
    private javax.swing.JPanel PanelMalaga2;
    private javax.swing.JPanel PanelMalaga3;
    private javax.swing.JPanel PanelMalaga4;
    private javax.swing.JPanel PanelMalaga6;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel TituloMalaga;
    private javax.swing.JLabel TituloMalaga1;
    private javax.swing.JLabel TituloMalaga2;
    private javax.swing.JLabel TituloMalaga3;
    private javax.swing.JLabel TituloMalaga4;
    private javax.swing.JLabel TituloMalaga6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
