/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package repaso;

import java.awt.Color;

/**
 *
 * @author Hp
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        TextoClick = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Campo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setBackground(new java.awt.Color(255, 102, 102));
        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoClick.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextoClick.setForeground(new java.awt.Color(255, 255, 102));
        TextoClick.setText("Clickame");
        Panel.add(TextoClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        jLabel1.setText("Soy Gris");
        jLabel1.setToolTipText("");
        Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 90, -1));

        Campo.setText("Hola");
        Campo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CampoKeyPressed(evt);
            }
        });
        Panel.add(Campo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CampoKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyChar()=='a'){
            jLabel1.setForeground(Color.yellow);
            jLabel1.setText("Soy amarillo");
         }
    }//GEN-LAST:event_CampoKeyPressed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Campo;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel TextoClick;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
