/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;

/**
 *
 * @author Hp
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        InsertarCliente = new javax.swing.JLabel();
        BotonClientes = new javax.swing.JButton();
        CerrarImagen = new javax.swing.JLabel();
        FirmaRock = new javax.swing.JLabel();
        FotoRock = new javax.swing.JLabel();
        FirmaArtic = new javax.swing.JLabel();
        FotoArtic = new javax.swing.JLabel();
        FirmaCad = new javax.swing.JLabel();
        FotoCad = new javax.swing.JLabel();
        FirmaGary = new javax.swing.JLabel();
        FotoGary = new javax.swing.JLabel();
        TextoRock = new javax.swing.JLabel();
        TextoArtic = new javax.swing.JLabel();
        TextoCad = new javax.swing.JLabel();
        TextoGary = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Editar2 = new javax.swing.JLabel();
        Editar3 = new javax.swing.JLabel();
        Editar4 = new javax.swing.JLabel();
        LibroFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InsertarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruzpequeña.png"))); // NOI18N
        InsertarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InsertarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InsertarClienteMouseExited(evt);
            }
        });
        Panel.add(InsertarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        BotonClientes.setBackground(new java.awt.Color(255, 204, 51));
        BotonClientes.setFont(new java.awt.Font("Burbank Big Rg Bk", 3, 24)); // NOI18N
        BotonClientes.setForeground(new java.awt.Color(117, 88, 13));
        BotonClientes.setText("Menu");
        BotonClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BotonClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonClientesMouseExited(evt);
            }
        });
        Panel.add(BotonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 110, 30));

        CerrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        CerrarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarImagenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarImagenMouseExited(evt);
            }
        });
        Panel.add(CerrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 40, -1));

        FirmaRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rockhopper_sig (1).png"))); // NOI18N
        Panel.add(FirmaRock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        FotoRock.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        FotoRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rockho.png"))); // NOI18N
        Panel.add(FotoRock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 240));

        FirmaArtic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arctic_sig (1).png"))); // NOI18N
        Panel.add(FirmaArtic, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, -1, -1));

        FotoArtic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Aunt.png"))); // NOI18N
        Panel.add(FotoArtic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        FirmaCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cadence_27s_Signature (1).png"))); // NOI18N
        Panel.add(FirmaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, -1));

        FotoCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cad.png"))); // NOI18N
        Panel.add(FotoCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        FirmaGary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Big_Big_Gary_Sig (1).png"))); // NOI18N
        Panel.add(FirmaGary, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));

        FotoGary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/G.png"))); // NOI18N
        Panel.add(FotoGary, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, -1, -1));

        TextoRock.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        TextoRock.setForeground(new java.awt.Color(80, 112, 150));
        TextoRock.setText("<html> Nombre: Aunt Artic <br> Direccion: Iglu <br> ID: 0002 <br> Telefono: 1235 <br>Fecha de registro: 09/05/1998 <br> Historial de compras: 05/04/2023 <br> Membresia: Activa");
        Panel.add(TextoRock, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 250, -1));

        TextoArtic.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        TextoArtic.setForeground(new java.awt.Color(80, 112, 150));
        TextoArtic.setText("<html> Nombre: DJ Cadence <br> Direccion:Discoteca<br> ID: 0003 <br> Telefono: 8888 <br>Fecha de registro: 12/11/2022 <br> Historial de compras: 28/01/2023 <br> Membresia: Activa");
        Panel.add(TextoArtic, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 200, -1));

        TextoCad.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        TextoCad.setForeground(new java.awt.Color(80, 112, 150));
        TextoCad.setText("<html> Nombre: Gary <br> Direccion: EPF <br> ID: 0004 <br> Telefono: 0000 <br>Fecha de registro: 01/04/1980 <br> Historial de compras: 25/12/2023 <br> Membresia: Activa");
        Panel.add(TextoCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 250, -1));

        TextoGary.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        TextoGary.setForeground(new java.awt.Color(80, 112, 150));
        TextoGary.setText("<html> Nombre: Captain Rockhopper <br> Direccion:The Migrator<br> ID: 0001 <br> Telefono: 1234 <br>Fecha de registro: 10/08/2002 <br> Historial de compras: 05/01/2003 <br> Membresia: Activa");
        Panel.add(TextoGary, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 250, -1));

        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png"))); // NOI18N
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });
        Panel.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, -1, -1));

        Editar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png"))); // NOI18N
        Editar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Editar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Editar2MouseExited(evt);
            }
        });
        Panel.add(Editar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, -1, -1));

        Editar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png"))); // NOI18N
        Editar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Editar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Editar3MouseExited(evt);
            }
        });
        Panel.add(Editar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 470, -1, -1));

        Editar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png"))); // NOI18N
        Editar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Editar4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Editar4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Editar4MouseExited(evt);
            }
        });
        Panel.add(Editar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        LibroFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Librofondo.png"))); // NOI18N
        LibroFondo.setText("jLabel1");
        Panel.add(LibroFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarImagenMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarImagenMouseClicked

    private void BotonClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClientesMouseClicked
        Menu abrir = new Menu();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonClientesMouseClicked

    private void BotonClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClientesMouseEntered
        BotonClientes.setBackground(new Color(202,152,0));
    }//GEN-LAST:event_BotonClientesMouseEntered

    private void BotonClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClientesMouseExited
        BotonClientes.setBackground(new Color(255,204,51));
    }//GEN-LAST:event_BotonClientesMouseExited

    private void Editar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar4MouseClicked
        InfoCliente abrir = new InfoCliente();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);    }//GEN-LAST:event_Editar4MouseClicked

    private void InsertarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertarClienteMouseClicked
        RegistrarCliente abrir = new RegistrarCliente();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
    }//GEN-LAST:event_InsertarClienteMouseClicked

    private void Editar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar4MouseEntered
        Editar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño.png")));
    }//GEN-LAST:event_Editar4MouseEntered

    private void Editar4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar4MouseExited
        Editar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png")));
    }//GEN-LAST:event_Editar4MouseExited

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño.png")));
    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png")));
    }//GEN-LAST:event_EditarMouseExited

    private void Editar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar2MouseEntered
        Editar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño.png")));
    }//GEN-LAST:event_Editar2MouseEntered

    private void Editar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar2MouseExited
        Editar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png")));
    }//GEN-LAST:event_Editar2MouseExited

    private void Editar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar3MouseEntered
        Editar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño.png")));
    }//GEN-LAST:event_Editar3MouseEntered

    private void Editar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar3MouseExited
        Editar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png")));
    }//GEN-LAST:event_Editar3MouseExited

    private void CerrarImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarImagenMouseEntered
        CerrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png")));
    }//GEN-LAST:event_CerrarImagenMouseEntered

    private void CerrarImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarImagenMouseExited
        CerrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png")));
    }//GEN-LAST:event_CerrarImagenMouseExited

    private void InsertarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertarClienteMouseEntered
        InsertarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruzpequeña2.png")));
    }//GEN-LAST:event_InsertarClienteMouseEntered

    private void InsertarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertarClienteMouseExited
        InsertarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruzpequeña.png")));
    }//GEN-LAST:event_InsertarClienteMouseExited
   
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonClientes;
    private javax.swing.JLabel CerrarImagen;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Editar2;
    private javax.swing.JLabel Editar3;
    private javax.swing.JLabel Editar4;
    private javax.swing.JLabel FirmaArtic;
    private javax.swing.JLabel FirmaCad;
    private javax.swing.JLabel FirmaGary;
    private javax.swing.JLabel FirmaRock;
    private javax.swing.JLabel FotoArtic;
    private javax.swing.JLabel FotoCad;
    private javax.swing.JLabel FotoGary;
    private javax.swing.JLabel FotoRock;
    private javax.swing.JLabel InsertarCliente;
    private javax.swing.JLabel LibroFondo;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel TextoArtic;
    private javax.swing.JLabel TextoCad;
    private javax.swing.JLabel TextoGary;
    private javax.swing.JLabel TextoRock;
    // End of variables declaration//GEN-END:variables
}
