/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;

/**
 *
 * @author Hp
 */
public class Prestamo extends javax.swing.JFrame {

    /**
     * Creates new form Prestamo
     */
    public Prestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        InsertarCliente = new javax.swing.JLabel();
        BotonClientes = new javax.swing.JButton();
        CerrarImagen = new javax.swing.JLabel();
        FirmaRock = new javax.swing.JLabel();
        FirmaArtic = new javax.swing.JLabel();
        FirmaCad = new javax.swing.JLabel();
        FirmaGary = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Editar2 = new javax.swing.JLabel();
        Editar3 = new javax.swing.JLabel();
        Editar4 = new javax.swing.JLabel();
        TextoRock2 = new javax.swing.JLabel();
        LibroTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        TextoRock3 = new javax.swing.JLabel();
        TextoRock4 = new javax.swing.JLabel();
        TextoRock5 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        TextoTitul1 = new javax.swing.JLabel();
        TextoTitulo1 = new javax.swing.JLabel();
        Captai = new javax.swing.JLabel();
        Captai1 = new javax.swing.JLabel();
        Captai2 = new javax.swing.JLabel();
        Captai3 = new javax.swing.JLabel();
        Captai4 = new javax.swing.JLabel();
        Captai5 = new javax.swing.JLabel();
        Captai6 = new javax.swing.JLabel();
        Captai7 = new javax.swing.JLabel();
        Captai8 = new javax.swing.JLabel();
        Captai9 = new javax.swing.JLabel();
        Captai10 = new javax.swing.JLabel();
        Captai11 = new javax.swing.JLabel();
        Captai12 = new javax.swing.JLabel();
        Captai13 = new javax.swing.JLabel();
        Captai14 = new javax.swing.JLabel();
        Captai15 = new javax.swing.JLabel();
        LibroFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        InsertarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruzpequeña.png"))); // NOI18N
        InsertarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertarClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InsertarClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InsertarClienteMouseExited(evt);
            }
        });
        Panel.add(InsertarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        BotonClientes.setBackground(new java.awt.Color(255, 204, 51));
        BotonClientes.setFont(new java.awt.Font("Burbank Big Rg Bk", 3, 24)); // NOI18N
        BotonClientes.setForeground(new java.awt.Color(117, 88, 13));
        BotonClientes.setText("Menu");
        BotonClientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        BotonClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonClientesMouseExited(evt);
            }
        });
        Panel.add(BotonClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 110, 30));

        CerrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        CerrarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarImagenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarImagenMouseExited(evt);
            }
        });
        Panel.add(CerrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 40, -1));

        FirmaRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rockhopper_sig (1).png"))); // NOI18N
        FirmaRock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FirmaRockMouseClicked(evt);
            }
        });
        Panel.add(FirmaRock, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        FirmaArtic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Arctic_sig (1).png"))); // NOI18N
        Panel.add(FirmaArtic, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, -1, -1));

        FirmaCad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cadence_27s_Signature (1).png"))); // NOI18N
        Panel.add(FirmaCad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        FirmaGary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Big_Big_Gary_Sig (1).png"))); // NOI18N
        Panel.add(FirmaGary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png"))); // NOI18N
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });
        Panel.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, -1, -1));

        Editar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png"))); // NOI18N
        Editar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Editar2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Editar2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Editar2MouseExited(evt);
            }
        });
        Panel.add(Editar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, -1, -1));

        Editar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png"))); // NOI18N
        Editar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Editar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Editar3MouseExited(evt);
            }
        });
        Panel.add(Editar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, -1, -1));

        Editar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png"))); // NOI18N
        Editar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Editar4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Editar4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Editar4MouseExited(evt);
            }
        });
        Panel.add(Editar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, -1, -1));

        TextoRock2.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 14)); // NOI18N
        TextoRock2.setForeground(new java.awt.Color(80, 112, 150));
        TextoRock2.setText("Fecha Prestamo");
        Panel.add(TextoRock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 130, -1));

        LibroTitulo.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 24)); // NOI18N
        LibroTitulo.setForeground(new java.awt.Color(80, 112, 150));
        LibroTitulo.setText("Clientes");
        Panel.add(LibroTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 110, -1));
        Panel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 890, 30));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Panel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 20, 470));
        Panel.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 900, 30));
        Panel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 900, 30));
        Panel.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 870, 30));

        TextoRock3.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 14)); // NOI18N
        TextoRock3.setForeground(new java.awt.Color(80, 112, 150));
        TextoRock3.setText("Fecha Devolucion");
        Panel.add(TextoRock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 130, -1));

        TextoRock4.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 24)); // NOI18N
        TextoRock4.setForeground(new java.awt.Color(80, 112, 150));
        TextoRock4.setText("Observacion");
        Panel.add(TextoRock4, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 150, -1));

        TextoRock5.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 24)); // NOI18N
        TextoRock5.setForeground(new java.awt.Color(80, 112, 150));
        TextoRock5.setText("Titulo");
        Panel.add(TextoRock5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 80, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Panel.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 20, 470));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Panel.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 20, 470));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Panel.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 20, 470));

        TextoTitul1.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 36)); // NOI18N
        TextoTitul1.setForeground(new java.awt.Color(255, 88, 13));
        TextoTitul1.setText("Biblioteca");
        Panel.add(TextoTitul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 200, -1));

        TextoTitulo1.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 36)); // NOI18N
        TextoTitulo1.setForeground(new java.awt.Color(255, 88, 13));
        TextoTitulo1.setText("Cafeteria");
        Panel.add(TextoTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 180, -1));

        Captai.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai.setForeground(new java.awt.Color(0, 0, 0));
        Captai.setText("<html>Cubierta <br>rasgada");
        Panel.add(Captai, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 90, -1));

        Captai1.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai1.setForeground(new java.awt.Color(0, 0, 0));
        Captai1.setText("<html>Burns out of <br>Bulbs");
        Panel.add(Captai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 150, -1));

        Captai2.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai2.setForeground(new java.awt.Color(0, 0, 0));
        Captai2.setText("<html>The Spice of <br>Life");
        Panel.add(Captai2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 150, -1));

        Captai3.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai3.setForeground(new java.awt.Color(0, 0, 0));
        Captai3.setText("<html>The journal of <br>Captain Rockhopper");
        Captai3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Captai3MouseClicked(evt);
            }
        });
        Panel.add(Captai3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 150, -1));

        Captai4.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai4.setForeground(new java.awt.Color(0, 0, 0));
        Captai4.setText("<html>The journal of <br>Captain Rockhopper");
        Panel.add(Captai4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 150, -1));

        Captai5.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai5.setForeground(new java.awt.Color(0, 0, 0));
        Captai5.setText("27/11/2023");
        Panel.add(Captai5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 120, -1));

        Captai6.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai6.setForeground(new java.awt.Color(0, 0, 0));
        Captai6.setText("01/12/2023");
        Panel.add(Captai6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 490, 120, -1));

        Captai7.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai7.setForeground(new java.awt.Color(0, 0, 0));
        Captai7.setText("12/12/2006");
        Panel.add(Captai7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 120, -1));

        Captai8.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai8.setForeground(new java.awt.Color(0, 0, 0));
        Captai8.setText("15/05/2012");
        Panel.add(Captai8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 280, 120, -1));

        Captai9.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai9.setForeground(new java.awt.Color(0, 0, 0));
        Captai9.setText("01/01/2024");
        Panel.add(Captai9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, 120, -1));

        Captai10.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai10.setForeground(new java.awt.Color(0, 0, 0));
        Captai10.setText("25/12/2023");
        Panel.add(Captai10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 120, -1));

        Captai11.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai11.setForeground(new java.awt.Color(0, 0, 0));
        Captai11.setText("05/02/2012");
        Panel.add(Captai11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 120, -1));

        Captai12.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai12.setForeground(new java.awt.Color(0, 0, 0));
        Captai12.setText("05/02/2012");
        Panel.add(Captai12, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 120, -1));

        Captai13.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai13.setForeground(new java.awt.Color(0, 0, 0));
        Captai13.setText("<html>Perfecto <br>Estado");
        Panel.add(Captai13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 90, -1));

        Captai14.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai14.setForeground(new java.awt.Color(0, 0, 0));
        Captai14.setText("<html>Pequeño<br>desperfecto");
        Panel.add(Captai14, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 490, 110, -1));

        Captai15.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Captai15.setForeground(new java.awt.Color(0, 0, 0));
        Captai15.setText("<html>Perfecto <br>Estado");
        Panel.add(Captai15, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 170, 90, -1));

        LibroFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/LibrofondoAzul.png"))); // NOI18N
        Panel.add(LibroFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertarClienteMouseClicked
        RegistrarPrestamo abrir = new RegistrarPrestamo();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
    }//GEN-LAST:event_InsertarClienteMouseClicked

    private void BotonClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClientesMouseClicked
        Menu abrir = new Menu();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_BotonClientesMouseClicked

    private void BotonClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClientesMouseEntered
        BotonClientes.setBackground(new Color(202,152,0));
    }//GEN-LAST:event_BotonClientesMouseEntered

    private void BotonClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonClientesMouseExited
        BotonClientes.setBackground(new Color(255,204,51));
    }//GEN-LAST:event_BotonClientesMouseExited

    private void CerrarImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarImagenMouseClicked
        System.exit(0);
    }//GEN-LAST:event_CerrarImagenMouseClicked

    private void Editar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar4MouseClicked
        InfoCliente abrir = new InfoCliente();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
    }//GEN-LAST:event_Editar4MouseClicked

    private void FirmaRockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FirmaRockMouseClicked
        InfoCliente abrir = new InfoCliente();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
    }//GEN-LAST:event_FirmaRockMouseClicked

    private void Editar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar2MouseClicked
        EditarPrestamo abrir = new EditarPrestamo();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
            }//GEN-LAST:event_Editar2MouseClicked

    private void Captai3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Captai3MouseClicked
        InfoLibro abrir = new InfoLibro();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);    }//GEN-LAST:event_Captai3MouseClicked

    private void Editar4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar4MouseEntered
        Editar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño.png")));
    }//GEN-LAST:event_Editar4MouseEntered

    private void Editar4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar4MouseExited
        Editar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png")));
    }//GEN-LAST:event_Editar4MouseExited

    private void Editar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar2MouseEntered
        Editar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño.png")));
    }//GEN-LAST:event_Editar2MouseEntered

    private void Editar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar2MouseExited
        Editar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png")));
    }//GEN-LAST:event_Editar2MouseExited

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño.png")));
    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png")));
    }//GEN-LAST:event_EditarMouseExited

    private void Editar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar3MouseEntered
        Editar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño.png")));
    }//GEN-LAST:event_Editar3MouseEntered

    private void Editar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Editar3MouseExited
        Editar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png")));
    }//GEN-LAST:event_Editar3MouseExited

    private void CerrarImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarImagenMouseEntered
        CerrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png")));
    }//GEN-LAST:event_CerrarImagenMouseEntered

    private void CerrarImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarImagenMouseExited
        CerrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png")));
    }//GEN-LAST:event_CerrarImagenMouseExited

    private void InsertarClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertarClienteMouseEntered
        InsertarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruzpequeña2.png")));
    }//GEN-LAST:event_InsertarClienteMouseEntered

    private void InsertarClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertarClienteMouseExited
        InsertarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cruzpequeña.png")));
    }//GEN-LAST:event_InsertarClienteMouseExited

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonClientes;
    private javax.swing.JLabel Captai;
    private javax.swing.JLabel Captai1;
    private javax.swing.JLabel Captai10;
    private javax.swing.JLabel Captai11;
    private javax.swing.JLabel Captai12;
    private javax.swing.JLabel Captai13;
    private javax.swing.JLabel Captai14;
    private javax.swing.JLabel Captai15;
    private javax.swing.JLabel Captai2;
    private javax.swing.JLabel Captai3;
    private javax.swing.JLabel Captai4;
    private javax.swing.JLabel Captai5;
    private javax.swing.JLabel Captai6;
    private javax.swing.JLabel Captai7;
    private javax.swing.JLabel Captai8;
    private javax.swing.JLabel Captai9;
    private javax.swing.JLabel CerrarImagen;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Editar2;
    private javax.swing.JLabel Editar3;
    private javax.swing.JLabel Editar4;
    private javax.swing.JLabel FirmaArtic;
    private javax.swing.JLabel FirmaCad;
    private javax.swing.JLabel FirmaGary;
    private javax.swing.JLabel FirmaRock;
    private javax.swing.JLabel InsertarCliente;
    private javax.swing.JLabel LibroFondo;
    private javax.swing.JLabel LibroTitulo;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel TextoRock2;
    private javax.swing.JLabel TextoRock3;
    private javax.swing.JLabel TextoRock4;
    private javax.swing.JLabel TextoRock5;
    private javax.swing.JLabel TextoTitul1;
    private javax.swing.JLabel TextoTitulo1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    // End of variables declaration//GEN-END:variables

    void setLocatioRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
