/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author Hp
 */
public class InfoCliente extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public InfoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Panel = new javax.swing.JPanel();
        CerrarImagen = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Libro1 = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        ImagenFondo = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Book_RoomFondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CerrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        CerrarImagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CerrarImagenMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CerrarImagenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CerrarImagenMouseExited(evt);
            }
        });
        Panel.add(CerrarImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 40, -1));

        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png"))); // NOI18N
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });
        Panel.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        Libro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Rockho.png"))); // NOI18N
        Panel.add(Libro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        Texto.setFont(new java.awt.Font("Burbank Big Rg Bk", 1, 18)); // NOI18N
        Texto.setForeground(new java.awt.Color(80, 112, 150));
        Texto.setText("<html> Nombre: Captain Rockhopper <br> Direccion:The Migrator<br> ID: 0001 <br> Telefono: 1234 <br>Fecha de registro: 10/08/2002 <br> Historial de compras: 05/01/2003 <br> Membresia: Activa");
        Panel.add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 420, -1));

        ImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Librofondo.png"))); // NOI18N
        ImagenFondo.setText("jLabel1");
        Panel.add(ImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 540, 600));

        getContentPane().add(Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CerrarImagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarImagenMouseClicked
        setVisible(false);
        dispose();
     }//GEN-LAST:event_CerrarImagenMouseClicked

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        EditarCliente abrir = new EditarCliente();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);    }//GEN-LAST:event_EditarMouseClicked

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño.png")));
    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pencilpequeño2.png")));
    }//GEN-LAST:event_EditarMouseExited

    private void CerrarImagenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarImagenMouseEntered
        CerrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar2.png")));
    }//GEN-LAST:event_CerrarImagenMouseEntered

    private void CerrarImagenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CerrarImagenMouseExited
        CerrarImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png")));
    }//GEN-LAST:event_CerrarImagenMouseExited
   
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CerrarImagen;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel ImagenFondo;
    private javax.swing.JLabel Libro1;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
