/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */
public class Cafeteria extends javax.swing.JFrame {

    /**
     * Creates new form Cafeteria
     */
    public Cafeteria() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1MenuPrincipal = new javax.swing.JPanel();
        jPanel2Central = new javax.swing.JPanel();
        jLabel1TelefonoTexto = new javax.swing.JLabel();
        jLabel1SucursalTexto = new javax.swing.JLabel();
        jLabel1HorarioTexto = new javax.swing.JLabel();
        jLabel1TelefonoLogo = new javax.swing.JLabel();
        jLabel1HorarioLogo = new javax.swing.JLabel();
        jLabel1SucursalesLogo = new javax.swing.JLabel();
        jLabel1EventosTexto1 = new javax.swing.JLabel();
        jLabel1ReservasTexto2 = new javax.swing.JLabel();
        jLabel1CartaTexto3 = new javax.swing.JLabel();
        jLabel1ReservaLogo = new javax.swing.JLabel();
        jLabel1CartaLogo = new javax.swing.JLabel();
        jLabel1EventoLogo = new javax.swing.JLabel();
        jPanel2Superior = new javax.swing.JPanel();
        jLabel1Minimizar = new javax.swing.JLabel();
        jLabel1Cerrar = new javax.swing.JLabel();
        jPanel2Lateral1 = new javax.swing.JPanel();
        jLabel2Contraseña1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1SendEnviar1 = new javax.swing.JButton();
        jLabel1Logo = new javax.swing.JLabel();
        jLabel1Usuario2 = new javax.swing.JLabel();
        jLabel1LogoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1050, 575));

        jPanel1MenuPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1MenuPrincipal.setPreferredSize(new java.awt.Dimension(1050, 575));
        jPanel1MenuPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2Central.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Central.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1TelefonoTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1TelefonoTexto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1TelefonoTexto.setText("TELÉFONOS");
        jPanel2Central.add(jLabel1TelefonoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 106, -1));

        jLabel1SucursalTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1SucursalTexto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto.setText("SUCURSALES");
        jPanel2Central.add(jLabel1SucursalTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 125, -1));

        jLabel1HorarioTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1HorarioTexto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1HorarioTexto.setText("HORARIOS");
        jPanel2Central.add(jLabel1HorarioTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 106, -1));

        jLabel1TelefonoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/llamada-telefonica.png"))); // NOI18N
        jLabel1TelefonoLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1TelefonoLogoMouseClicked(evt);
            }
        });
        jPanel2Central.add(jLabel1TelefonoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jLabel1HorarioLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/abierto.png"))); // NOI18N
        jLabel1HorarioLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1HorarioLogoMouseClicked(evt);
            }
        });
        jPanel2Central.add(jLabel1HorarioLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, -1, -1));

        jLabel1SucursalesLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/Sucursales.png"))); // NOI18N
        jLabel1SucursalesLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1SucursalesLogoMouseClicked(evt);
            }
        });
        jPanel2Central.add(jLabel1SucursalesLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel1EventosTexto1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1EventosTexto1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1EventosTexto1.setText("EVENTOS");
        jPanel2Central.add(jLabel1EventosTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 90, -1));

        jLabel1ReservasTexto2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1ReservasTexto2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1ReservasTexto2.setText("RESERVAS");
        jPanel2Central.add(jLabel1ReservasTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 106, -1));

        jLabel1CartaTexto3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1CartaTexto3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1CartaTexto3.setText("CARTA");
        jPanel2Central.add(jLabel1CartaTexto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 70, -1));

        jLabel1ReservaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/reservado.png"))); // NOI18N
        jLabel1ReservaLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1ReservaLogoMouseClicked(evt);
            }
        });
        jPanel2Central.add(jLabel1ReservaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, -1));

        jLabel1CartaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/menu.png"))); // NOI18N
        jLabel1CartaLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1CartaLogoMouseClicked(evt);
            }
        });
        jPanel2Central.add(jLabel1CartaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLabel1EventoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/calendario.png"))); // NOI18N
        jLabel1EventoLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1EventoLogoMouseClicked(evt);
            }
        });
        jPanel2Central.add(jLabel1EventoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        jPanel1MenuPrincipal.add(jPanel2Central, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 810, 530));

        jPanel2Superior.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Superior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/minimizar.png"))); // NOI18N
        jPanel2Superior.add(jLabel1Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 37, -1));

        jLabel1Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cerrar.png"))); // NOI18N
        jPanel2Superior.add(jLabel1Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 37, -1));

        jPanel1MenuPrincipal.add(jPanel2Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 760, 50));

        jPanel2Lateral1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Lateral1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2Lateral1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2Contraseña1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña1.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña1.setText("Usuario:");
        jPanel2Lateral1.add(jLabel2Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 293, 88, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Ingrese su usuario o email");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2Lateral1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 324, 140, -1));

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2Lateral1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 396, 140, -1));

        jButton1SendEnviar1.setBackground(new java.awt.Color(120, 77, 60));
        jButton1SendEnviar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1SendEnviar1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1SendEnviar1.setText("ENVIAR");
        jButton1SendEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SendEnviar1ActionPerformed(evt);
            }
        });
        jPanel2Lateral1.add(jButton1SendEnviar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 431, 80, 42));

        jLabel1Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/logo.jpg"))); // NOI18N
        jPanel2Lateral1.add(jLabel1Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 158, -1));

        jLabel1Usuario2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1Usuario2.setForeground(new java.awt.Color(120, 77, 60));
        jLabel1Usuario2.setText("Contraseña:");
        jPanel2Lateral1.add(jLabel1Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 365, 106, -1));

        jLabel1LogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/menuhamburguesa.png"))); // NOI18N
        jPanel2Lateral1.add(jLabel1LogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1MenuPrincipal.add(jPanel2Lateral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SendEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SendEnviar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1SendEnviar1ActionPerformed

    private void jLabel1SucursalesLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1SucursalesLogoMouseClicked
         cafeteriaSucursales abrir = new cafeteriaSucursales();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1SucursalesLogoMouseClicked

    private void jLabel1TelefonoLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1TelefonoLogoMouseClicked
        cafeteriaTelefono abrir = new cafeteriaTelefono();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_jLabel1TelefonoLogoMouseClicked

    private void jLabel1HorarioLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1HorarioLogoMouseClicked
cafeteriaHorarios abrir = new cafeteriaHorarios();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jLabel1HorarioLogoMouseClicked

    private void jLabel1EventoLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1EventoLogoMouseClicked
cafeteriaEventos abrir = new cafeteriaEventos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jLabel1EventoLogoMouseClicked

    private void jLabel1CartaLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1CartaLogoMouseClicked
cafeteriaCarta abrir = new cafeteriaCarta();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_jLabel1CartaLogoMouseClicked

    private void jLabel1ReservaLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1ReservaLogoMouseClicked
cafeteriaReservas abrir = new cafeteriaReservas();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_jLabel1ReservaLogoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafeteria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1SendEnviar1;
    private javax.swing.JLabel jLabel1CartaLogo;
    private javax.swing.JLabel jLabel1CartaTexto3;
    private javax.swing.JLabel jLabel1Cerrar;
    private javax.swing.JLabel jLabel1EventoLogo;
    private javax.swing.JLabel jLabel1EventosTexto1;
    private javax.swing.JLabel jLabel1HorarioLogo;
    private javax.swing.JLabel jLabel1HorarioTexto;
    private javax.swing.JLabel jLabel1Logo;
    private javax.swing.JLabel jLabel1LogoMenu;
    private javax.swing.JLabel jLabel1Minimizar;
    private javax.swing.JLabel jLabel1ReservaLogo;
    private javax.swing.JLabel jLabel1ReservasTexto2;
    private javax.swing.JLabel jLabel1SucursalTexto;
    private javax.swing.JLabel jLabel1SucursalesLogo;
    private javax.swing.JLabel jLabel1TelefonoLogo;
    private javax.swing.JLabel jLabel1TelefonoTexto;
    private javax.swing.JLabel jLabel1Usuario2;
    private javax.swing.JLabel jLabel2Contraseña1;
    private javax.swing.JPanel jPanel1MenuPrincipal;
    private javax.swing.JPanel jPanel2Central;
    private javax.swing.JPanel jPanel2Lateral1;
    private javax.swing.JPanel jPanel2Superior;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
