/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */
public class cafeteriaCarta extends javax.swing.JFrame {

    /**
     * Creates new form cafeteriaCarta
     */
    public cafeteriaCarta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1MenuTelefono = new javax.swing.JPanel();
        jPanel2Central2 = new javax.swing.JPanel();
        jPanel2Lateral1Inferior3 = new javax.swing.JPanel();
        jLabel2Contraseña22 = new javax.swing.JLabel();
        jLabel2Contraseña23 = new javax.swing.JLabel();
        jLabel1SucursalTexto60 = new javax.swing.JLabel();
        jLabel2Contraseña25 = new javax.swing.JLabel();
        jLabel1SucursalTexto64 = new javax.swing.JLabel();
        jLabel2Contraseña1 = new javax.swing.JLabel();
        jLabel2Contraseña3 = new javax.swing.JLabel();
        jLabel2Contraseña26 = new javax.swing.JLabel();
        jLabel2Contraseña27 = new javax.swing.JLabel();
        jLabel1SucursalTexto68 = new javax.swing.JLabel();
        jLabel1SucursalTexto69 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jPanel2Superior3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1SucursalTexto19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1SucursalTexto21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1SucursalTexto22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1SucursalTexto23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel1SucursalTexto25 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel1SucursalTexto26 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel1SucursalTexto37 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1Cerrar = new javax.swing.JLabel();
        jLabel1Minimizar = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel1SucursalTexto38 = new javax.swing.JLabel();
        jPanel2Lateral1 = new javax.swing.JPanel();
        jLabel2Contraseña4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1SendEnviar1 = new javax.swing.JButton();
        jLabel1Logo = new javax.swing.JLabel();
        jLabel1Usuario2 = new javax.swing.JLabel();
        jLabel1LogoMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1MenuTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1MenuTelefono.setPreferredSize(new java.awt.Dimension(1050, 575));
        jPanel1MenuTelefono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2Central2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Central2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2Lateral1Inferior3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Lateral1Inferior3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2Central2.add(jPanel2Lateral1Inferior3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jLabel2Contraseña22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2Contraseña22.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña22.setText("Espresso ");
        jPanel2Central2.add(jLabel2Contraseña22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, 80, -1));

        jLabel2Contraseña23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2Contraseña23.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña23.setText("Chocolates");
        jPanel2Central2.add(jLabel2Contraseña23, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 110, -1));

        jLabel1SucursalTexto60.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1SucursalTexto60.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto60.setText("<html>Descubre nuestros chocolates y sus mejores combinaciones, calientes o fríos... ¡Tú decides!  ");
        jPanel2Central2.add(jLabel1SucursalTexto60, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 220, 60));

        jLabel2Contraseña25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2Contraseña25.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2Contraseña25.setText(" de suave crema");
        jPanel2Central2.add(jLabel2Contraseña25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 160, 30));

        jLabel1SucursalTexto64.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1SucursalTexto64.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto64.setText("<html>Bebidas refrescantes de hielo batido, con base de café con diferentes variedades de sabores, mezclados con leche o bebidas vegetales  ");
        jPanel2Central2.add(jLabel1SucursalTexto64, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 190, -1));

        jLabel2Contraseña1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2Contraseña1.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña1.setText("BEBIDAS");
        jPanel2Central2.add(jLabel2Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 160, -1));

        jLabel2Contraseña3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2Contraseña3.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña3.setText("FRAPUCCINO®");
        jPanel2Central2.add(jLabel2Contraseña3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, -1));

        jLabel2Contraseña26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2Contraseña26.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2Contraseña26.setText("Con base  ");
        jPanel2Central2.add(jLabel2Contraseña26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, 30));

        jLabel2Contraseña27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2Contraseña27.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2Contraseña27.setText("Con base  de café");
        jPanel2Central2.add(jLabel2Contraseña27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 160, 30));

        jLabel1SucursalTexto68.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1SucursalTexto68.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto68.setText("<html>Bebidas con los mejores granos de <br> café 100% arábica, cuidadosamente seleccionados y tostados.");
        jPanel2Central2.add(jLabel1SucursalTexto68, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 190, -1));

        jLabel1SucursalTexto69.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel1SucursalTexto69.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto69.setText("<html>Bebidas refrescantes de hielo batido con una dulce base de crema <br>leches o bebidas vegetales y nata montada. Puedes elegir entre diferentes variedades de sabores.  ");
        jPanel2Central2.add(jLabel1SucursalTexto69, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2Central2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 130, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/1.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel2Central2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 130, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/4.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel2Central2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 130, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/2.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel2Central2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 130, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/vaso-de-cafe .png"))); // NOI18N
        jPanel2Central2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/taza-de-cafe-con-espuma.png"))); // NOI18N
        jPanel2Central2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/flecha-correcta-derecha.png"))); // NOI18N
        jPanel2Central2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/flecha-correcta-Izquiera.png"))); // NOI18N
        jPanel2Central2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 420, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/coffee-stains-on-a-vintage-paper-background-concept-free-vector.jpg"))); // NOI18N
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 102, 0), 5));
        jPanel2Central2.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 770, 340));

        jPanel1MenuTelefono.add(jPanel2Central2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 810, 520));

        jPanel2Superior3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Superior3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1SucursalTexto19.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto19.setText("SUCURSALES");
        jPanel1.add(jLabel1SucursalTexto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 70, -1));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/Sucursales.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jPanel2Superior3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/evento.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto21.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto21.setText("EVENTOS");
        jPanel2.add(jLabel1SucursalTexto21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 150, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/abierto.png"))); // NOI18N
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto22.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto22.setText("HORARIOS");
        jPanel4.add(jLabel1SucursalTexto22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, 60));

        jPanel3.setBackground(new java.awt.Color(120, 77, 60));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/menuBlanco.png"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto23.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1SucursalTexto23.setText("CARTA");
        jPanel3.add(jLabel1SucursalTexto23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, 60));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/llamada-telefonica.png"))); // NOI18N
        jPanel7.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto25.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto25.setText("TELÉFONO");
        jPanel7.add(jLabel1SucursalTexto25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 150, 60));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/abierto.png"))); // NOI18N
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto26.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto26.setText("HORARIOS");
        jPanel8.add(jLabel1SucursalTexto26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, 60));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel13MouseClicked(evt);
            }
        });
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/llamada-telefonica.png"))); // NOI18N
        jPanel13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto37.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto37.setText("TELÉFONO");
        jPanel13.add(jLabel1SucursalTexto37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 150, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cerrar.png"))); // NOI18N
        jPanel5.add(jLabel1Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 37, -1));

        jLabel1Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/minimizar.png"))); // NOI18N
        jLabel1Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MinimizarMouseClicked(evt);
            }
        });
        jPanel5.add(jLabel1Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 37, -1));

        jPanel2Superior3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 160, 60));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/reservado.png"))); // NOI18N
        jPanel14.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto38.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto38.setText("RESERVAS");
        jPanel14.add(jLabel1SucursalTexto38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 150, 60));

        jPanel1MenuTelefono.add(jPanel2Superior3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 60));

        jPanel2Lateral1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Lateral1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2Lateral1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2Contraseña4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña4.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña4.setText("Usuario:");
        jPanel2Lateral1.add(jLabel2Contraseña4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 293, 88, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Ingrese su usuario o email");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2Lateral1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 324, 140, -1));

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2Lateral1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 396, 140, -1));

        jButton1SendEnviar1.setBackground(new java.awt.Color(120, 77, 60));
        jButton1SendEnviar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1SendEnviar1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1SendEnviar1.setText("ENVIAR");
        jButton1SendEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SendEnviar1ActionPerformed(evt);
            }
        });
        jPanel2Lateral1.add(jButton1SendEnviar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 431, 80, 42));

        jLabel1Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/logo.jpg"))); // NOI18N
        jPanel2Lateral1.add(jLabel1Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 158, -1));

        jLabel1Usuario2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1Usuario2.setForeground(new java.awt.Color(120, 77, 60));
        jLabel1Usuario2.setText("Contraseña:");
        jPanel2Lateral1.add(jLabel1Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 365, 106, -1));

        jLabel1LogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/menuhamburguesa.png"))); // NOI18N
        jPanel2Lateral1.add(jLabel1LogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1MenuTelefono.add(jPanel2Lateral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1MenuTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1MenuTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SendEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SendEnviar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1SendEnviar1ActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
cafeteriaSucursales abrir = new cafeteriaSucursales();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
cafeteriaHorarios abrir = new cafeteriaHorarios();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel13MouseClicked
 cafeteriaTelefono abrir = new cafeteriaTelefono();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);      }//GEN-LAST:event_jPanel13MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
cafeteriaEventos abrir = new cafeteriaEventos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
cafeteriaReservas abrir = new cafeteriaReservas();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_jPanel14MouseClicked

    private void jLabel1MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MinimizarMouseClicked
Cafeteria abrir = new Cafeteria();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_jLabel1MinimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cafeteriaCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cafeteriaCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cafeteriaCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cafeteriaCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cafeteriaCarta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jButton1SendEnviar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Cerrar;
    private javax.swing.JLabel jLabel1Logo;
    private javax.swing.JLabel jLabel1LogoMenu;
    private javax.swing.JLabel jLabel1Minimizar;
    private javax.swing.JLabel jLabel1SucursalTexto19;
    private javax.swing.JLabel jLabel1SucursalTexto21;
    private javax.swing.JLabel jLabel1SucursalTexto22;
    private javax.swing.JLabel jLabel1SucursalTexto23;
    private javax.swing.JLabel jLabel1SucursalTexto25;
    private javax.swing.JLabel jLabel1SucursalTexto26;
    private javax.swing.JLabel jLabel1SucursalTexto37;
    private javax.swing.JLabel jLabel1SucursalTexto38;
    private javax.swing.JLabel jLabel1SucursalTexto60;
    private javax.swing.JLabel jLabel1SucursalTexto64;
    private javax.swing.JLabel jLabel1SucursalTexto68;
    private javax.swing.JLabel jLabel1SucursalTexto69;
    private javax.swing.JLabel jLabel1Usuario2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel2Contraseña1;
    private javax.swing.JLabel jLabel2Contraseña22;
    private javax.swing.JLabel jLabel2Contraseña23;
    private javax.swing.JLabel jLabel2Contraseña25;
    private javax.swing.JLabel jLabel2Contraseña26;
    private javax.swing.JLabel jLabel2Contraseña27;
    private javax.swing.JLabel jLabel2Contraseña3;
    private javax.swing.JLabel jLabel2Contraseña4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel1MenuTelefono;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2Central2;
    private javax.swing.JPanel jPanel2Lateral1;
    private javax.swing.JPanel jPanel2Lateral1Inferior3;
    private javax.swing.JPanel jPanel2Superior3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
