/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hp
 */
public class cafeteriaTelefono extends javax.swing.JFrame {

    /**
     * Creates new form cafeteriaTelefono
     */
    public cafeteriaTelefono() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel1MenuTelefono = new javax.swing.JPanel();
        jPanel2Central2 = new javax.swing.JPanel();
        jPanel2Lateral1Inferior3 = new javax.swing.JPanel();
        jLabel2Contraseña8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel2Contraseña12 = new javax.swing.JLabel();
        jLabel1SucursalTexto31 = new javax.swing.JLabel();
        jLabel1SucursalTexto32 = new javax.swing.JLabel();
        jLabel1SucursalTexto34 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel2Contraseña22 = new javax.swing.JLabel();
        jLabel1SucursalTexto55 = new javax.swing.JLabel();
        jLabel1SucursalTexto56 = new javax.swing.JLabel();
        jLabel1SucursalTexto58 = new javax.swing.JLabel();
        jLabel2Contraseña23 = new javax.swing.JLabel();
        jLabel1SucursalTexto59 = new javax.swing.JLabel();
        jLabel1SucursalTexto61 = new javax.swing.JLabel();
        jLabel1SucursalTexto62 = new javax.swing.JLabel();
        jLabel2Contraseña24 = new javax.swing.JLabel();
        jLabel1SucursalTexto63 = new javax.swing.JLabel();
        jLabel1SucursalTexto64 = new javax.swing.JLabel();
        jLabel1SucursalTexto65 = new javax.swing.JLabel();
        jLabel2Contraseña25 = new javax.swing.JLabel();
        jLabel2Contraseña26 = new javax.swing.JLabel();
        jLabel1SucursalTexto66 = new javax.swing.JLabel();
        jLabel1SucursalTexto67 = new javax.swing.JLabel();
        jLabel1SucursalTexto68 = new javax.swing.JLabel();
        jLabel2Contraseña27 = new javax.swing.JLabel();
        jLabel1SucursalTexto69 = new javax.swing.JLabel();
        jLabel1SucursalTexto70 = new javax.swing.JLabel();
        jLabel1SucursalTexto71 = new javax.swing.JLabel();
        jLabel2Contraseña28 = new javax.swing.JLabel();
        jLabel1SucursalTexto72 = new javax.swing.JLabel();
        jLabel1SucursalTexto73 = new javax.swing.JLabel();
        jLabel1SucursalTexto74 = new javax.swing.JLabel();
        jLabel2Contraseña29 = new javax.swing.JLabel();
        jLabel1SucursalTexto75 = new javax.swing.JLabel();
        jLabel1SucursalTexto76 = new javax.swing.JLabel();
        jLabel1SucursalTexto77 = new javax.swing.JLabel();
        jLabel2Contraseña30 = new javax.swing.JLabel();
        jLabel2Contraseña31 = new javax.swing.JLabel();
        jLabel1SucursalTexto78 = new javax.swing.JLabel();
        jLabel1SucursalTexto79 = new javax.swing.JLabel();
        jLabel1SucursalTexto80 = new javax.swing.JLabel();
        jLabel2Contraseña32 = new javax.swing.JLabel();
        jLabel1SucursalTexto81 = new javax.swing.JLabel();
        jLabel1SucursalTexto82 = new javax.swing.JLabel();
        jLabel1SucursalTexto83 = new javax.swing.JLabel();
        jLabel2Contraseña33 = new javax.swing.JLabel();
        jLabel1SucursalTexto84 = new javax.swing.JLabel();
        jLabel1SucursalTexto85 = new javax.swing.JLabel();
        jLabel1SucursalTexto86 = new javax.swing.JLabel();
        jLabel2Contraseña34 = new javax.swing.JLabel();
        jLabel1SucursalTexto87 = new javax.swing.JLabel();
        jLabel1SucursalTexto88 = new javax.swing.JLabel();
        jLabel1SucursalTexto89 = new javax.swing.JLabel();
        jLabel2Contraseña35 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel2Contraseña3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel2Lateral1 = new javax.swing.JPanel();
        jLabel2Contraseña1 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton1SendEnviar1 = new javax.swing.JButton();
        jLabel1Logo = new javax.swing.JLabel();
        jLabel1Usuario2 = new javax.swing.JLabel();
        jLabel1LogoMenu = new javax.swing.JLabel();
        jPanel2Superior3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1SucursalTexto19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1SucursalTexto21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel1SucursalTexto22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel1SucursalTexto23 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel1SucursalTexto25 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel1SucursalTexto26 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel1SucursalTexto37 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1Cerrar = new javax.swing.JLabel();
        jLabel1Minimizar = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel58 = new javax.swing.JLabel();
        jLabel1SucursalTexto38 = new javax.swing.JLabel();

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1MenuTelefono.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1MenuTelefono.setPreferredSize(new java.awt.Dimension(1050, 575));
        jPanel1MenuTelefono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2Central2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Central2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2Lateral1Inferior3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Lateral1Inferior3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2Central2.add(jPanel2Lateral1Inferior3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, -1, -1));

        jLabel2Contraseña8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña8.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña8.setText("Ciudad:");
        jPanel2Central2.add(jLabel2Contraseña8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 90, 30));

        jTextField7.setBackground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("Sucursal Teatinos");
        jTextField7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel2Central2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 140, -1));

        jLabel2Contraseña12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña12.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña12.setText("Sucursales Málaga");
        jPanel2Central2.add(jLabel2Contraseña12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, -1));

        jLabel1SucursalTexto31.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto31.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto31.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 70, -1));

        jLabel1SucursalTexto32.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto32.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto32.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 50, 10));

        jLabel1SucursalTexto34.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto34.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 50, -1));

        jSeparator13.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator13.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2Central2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 750, 20));

        jLabel2Contraseña22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña22.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña22.setText("Centro");
        jPanel2Central2.add(jLabel2Contraseña22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 70, -1));

        jLabel1SucursalTexto55.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto55.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto55.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto55, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 70, -1));

        jLabel1SucursalTexto56.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto56.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto56.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto56, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 50, 10));

        jLabel1SucursalTexto58.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto58.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto58.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto58, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 50, -1));

        jLabel2Contraseña23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña23.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña23.setText("Larios");
        jPanel2Central2.add(jLabel2Contraseña23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, -1));

        jLabel1SucursalTexto59.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto59.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto59.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto59, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 70, -1));

        jLabel1SucursalTexto61.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto61.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto61.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto61, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 50, 10));

        jLabel1SucursalTexto62.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto62.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto62.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto62, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 50, -1));

        jLabel2Contraseña24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña24.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña24.setText("Vialia");
        jPanel2Central2.add(jLabel2Contraseña24, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 60, -1));

        jLabel1SucursalTexto63.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto63.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto63.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto63, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, 70, -1));

        jLabel1SucursalTexto64.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto64.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto64.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto64, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 50, 10));

        jLabel1SucursalTexto65.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto65.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto65.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto65, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 50, -1));

        jLabel2Contraseña25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña25.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña25.setText("Teatinos");
        jPanel2Central2.add(jLabel2Contraseña25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, -1));

        jLabel2Contraseña26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña26.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña26.setText("Sucursales Barcelona");
        jPanel2Central2.add(jLabel2Contraseña26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 180, -1));

        jLabel1SucursalTexto66.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto66.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto66.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto66, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 70, -1));

        jLabel1SucursalTexto67.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto67.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto67.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto67, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 50, 10));

        jLabel1SucursalTexto68.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto68.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto68.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto68, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 50, -1));

        jLabel2Contraseña27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña27.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña27.setText("Barceloneta");
        jPanel2Central2.add(jLabel2Contraseña27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 110, -1));

        jLabel1SucursalTexto69.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto69.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto69.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto69, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 70, -1));

        jLabel1SucursalTexto70.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto70.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto70.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto70, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 50, 10));

        jLabel1SucursalTexto71.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto71.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto71.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto71, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 50, -1));

        jLabel2Contraseña28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña28.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña28.setText("Junts");
        jPanel2Central2.add(jLabel2Contraseña28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 50, -1));

        jLabel1SucursalTexto72.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto72.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto72.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto72, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 70, -1));

        jLabel1SucursalTexto73.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto73.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto73.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto73, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 50, 10));

        jLabel1SucursalTexto74.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto74.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto74.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto74, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 50, -1));

        jLabel2Contraseña29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña29.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña29.setText("Llobregat");
        jPanel2Central2.add(jLabel2Contraseña29, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 80, -1));

        jLabel1SucursalTexto75.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto75.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto75.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto75, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 70, -1));

        jLabel1SucursalTexto76.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto76.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto76.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto76, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 50, 10));

        jLabel1SucursalTexto77.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto77.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto77.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto77, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 50, -1));

        jLabel2Contraseña30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña30.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña30.setText("Hospitalet");
        jPanel2Central2.add(jLabel2Contraseña30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, -1));

        jLabel2Contraseña31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña31.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña31.setText("Sucursales Madrid");
        jPanel2Central2.add(jLabel2Contraseña31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 160, -1));

        jLabel1SucursalTexto78.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto78.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto78.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto78, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 70, -1));

        jLabel1SucursalTexto79.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto79.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto79.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto79, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 50, 10));

        jLabel1SucursalTexto80.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto80.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto80.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto80, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 50, -1));

        jLabel2Contraseña32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña32.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña32.setText("Bernabeu");
        jPanel2Central2.add(jLabel2Contraseña32, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 90, 30));

        jLabel1SucursalTexto81.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto81.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto81.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto81, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 70, 10));

        jLabel1SucursalTexto82.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto82.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto82.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto82, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 50, 10));

        jLabel1SucursalTexto83.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto83.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto83.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto83, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 410, 50, 10));

        jLabel2Contraseña33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña33.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña33.setText("Prado");
        jPanel2Central2.add(jLabel2Contraseña33, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 50, -1));

        jLabel1SucursalTexto84.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto84.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto84.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto84, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 70, -1));

        jLabel1SucursalTexto85.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto85.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto85.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto85, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, 50, 10));

        jLabel1SucursalTexto86.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto86.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto86.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto86, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, 50, -1));

        jLabel2Contraseña34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña34.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña34.setText("Banco Nacional");
        jPanel2Central2.add(jLabel2Contraseña34, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 140, -1));

        jLabel1SucursalTexto87.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto87.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto87.setText("+34 666 22 58 14");
        jPanel2Central2.add(jLabel1SucursalTexto87, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 70, -1));

        jLabel1SucursalTexto88.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto88.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto88.setText("Calle 1234 ");
        jPanel2Central2.add(jLabel1SucursalTexto88, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 400, 50, 10));

        jLabel1SucursalTexto89.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel1SucursalTexto89.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto89.setText("Telefono");
        jPanel2Central2.add(jLabel1SucursalTexto89, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 410, 50, -1));

        jLabel2Contraseña35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña35.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña35.setText("Plaza Mayor");
        jPanel2Central2.add(jLabel2Contraseña35, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 110, -1));

        jSeparator16.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator16.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2Central2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 750, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/whatsappGrande.png"))); // NOI18N
        jPanel2Central2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/granos-de-cafe.png"))); // NOI18N
        jPanel2Central2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/flecha-correcta-derecha.png"))); // NOI18N
        jPanel2Central2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/flecha-correcta-derecha.png"))); // NOI18N
        jPanel2Central2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/flecha-correcta-derecha.png"))); // NOI18N
        jPanel2Central2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, -1, -1));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("29002");
        jTextField5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel2Central2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 140, -1));

        jLabel2Contraseña3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña3.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña3.setText("CP:");
        jPanel2Central2.add(jLabel2Contraseña3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 40, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, -1, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, -1, -1));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/ubicacion.png"))); // NOI18N
        jPanel2Central2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        jPanel1MenuTelefono.add(jPanel2Central2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 810, 520));

        jPanel2Lateral1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Lateral1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanel2Lateral1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2Contraseña1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2Contraseña1.setForeground(new java.awt.Color(120, 77, 60));
        jLabel2Contraseña1.setText("Usuario:");
        jPanel2Lateral1.add(jLabel2Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 293, 88, -1));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Ingrese su usuario o email");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2Lateral1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 324, 140, -1));

        jPasswordField2.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setText("jPasswordField1");
        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(204, 204, 204)));
        jPanel2Lateral1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 396, 140, -1));

        jButton1SendEnviar1.setBackground(new java.awt.Color(120, 77, 60));
        jButton1SendEnviar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1SendEnviar1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1SendEnviar1.setText("ENVIAR");
        jButton1SendEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1SendEnviar1ActionPerformed(evt);
            }
        });
        jPanel2Lateral1.add(jButton1SendEnviar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 431, 80, 42));

        jLabel1Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/logo.jpg"))); // NOI18N
        jPanel2Lateral1.add(jLabel1Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 158, -1));

        jLabel1Usuario2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1Usuario2.setForeground(new java.awt.Color(120, 77, 60));
        jLabel1Usuario2.setText("Contraseña:");
        jPanel2Lateral1.add(jLabel1Usuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 365, 106, -1));

        jLabel1LogoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/menuhamburguesa.png"))); // NOI18N
        jPanel2Lateral1.add(jLabel1LogoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1MenuTelefono.add(jPanel2Lateral1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 250, 520));

        jPanel2Superior3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2Superior3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1SucursalTexto19.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto19.setText("SUCURSALES");
        jPanel1.add(jLabel1SucursalTexto19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 70, -1));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/Sucursales.png"))); // NOI18N
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jPanel2Superior3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/evento.png"))); // NOI18N
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto21.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto21.setText("EVENTOS");
        jPanel2.add(jLabel1SucursalTexto21, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 150, 60));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/abierto.png"))); // NOI18N
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto22.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto22.setText("HORARIOS");
        jPanel4.add(jLabel1SucursalTexto22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/menu.png"))); // NOI18N
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto23.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto23.setText("CARTA");
        jPanel3.add(jLabel1SucursalTexto23, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, 60));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/llamada-telefonica.png"))); // NOI18N
        jPanel7.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto25.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto25.setText("TELÉFONO");
        jPanel7.add(jLabel1SucursalTexto25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 150, 60));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/abierto.png"))); // NOI18N
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto26.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto26.setText("HORARIOS");
        jPanel8.add(jLabel1SucursalTexto26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 150, 60));

        jPanel13.setBackground(new java.awt.Color(120, 77, 60));
        jPanel13.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/llamada-telefonicaBlanco.png"))); // NOI18N
        jPanel13.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto37.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1SucursalTexto37.setText("TELÉFONO");
        jPanel13.add(jLabel1SucursalTexto37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 150, 60));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/cerrar.png"))); // NOI18N
        jPanel5.add(jLabel1Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 37, -1));

        jLabel1Minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/minimizar.png"))); // NOI18N
        jLabel1Minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MinimizarMouseClicked(evt);
            }
        });
        jPanel5.add(jLabel1Minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 37, -1));

        jPanel2Superior3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 160, 60));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel14MouseClicked(evt);
            }
        });
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/96x96/54x54/reservado.png"))); // NOI18N
        jPanel14.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 60));

        jLabel1SucursalTexto38.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel1SucursalTexto38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1SucursalTexto38.setText("RESERVAS");
        jPanel14.add(jLabel1SucursalTexto38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, -1));

        jPanel2Superior3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 150, 60));

        jPanel1MenuTelefono.add(jPanel2Superior3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1MenuTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1MenuTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1SendEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1SendEnviar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1SendEnviar1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jLabel1MinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MinimizarMouseClicked
Cafeteria abrir = new Cafeteria();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jLabel1MinimizarMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
cafeteriaSucursales abrir = new cafeteriaSucursales();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
cafeteriaHorarios abrir = new cafeteriaHorarios();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
cafeteriaCarta abrir = new cafeteriaCarta();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
cafeteriaEventos abrir = new cafeteriaEventos();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel14MouseClicked
cafeteriaReservas abrir = new cafeteriaReservas();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jPanel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cafeteriaTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cafeteriaTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cafeteriaTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cafeteriaTelefono.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cafeteriaTelefono().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1SendEnviar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1Cerrar;
    private javax.swing.JLabel jLabel1Logo;
    private javax.swing.JLabel jLabel1LogoMenu;
    private javax.swing.JLabel jLabel1Minimizar;
    private javax.swing.JLabel jLabel1SucursalTexto19;
    private javax.swing.JLabel jLabel1SucursalTexto21;
    private javax.swing.JLabel jLabel1SucursalTexto22;
    private javax.swing.JLabel jLabel1SucursalTexto23;
    private javax.swing.JLabel jLabel1SucursalTexto25;
    private javax.swing.JLabel jLabel1SucursalTexto26;
    private javax.swing.JLabel jLabel1SucursalTexto31;
    private javax.swing.JLabel jLabel1SucursalTexto32;
    private javax.swing.JLabel jLabel1SucursalTexto34;
    private javax.swing.JLabel jLabel1SucursalTexto37;
    private javax.swing.JLabel jLabel1SucursalTexto38;
    private javax.swing.JLabel jLabel1SucursalTexto55;
    private javax.swing.JLabel jLabel1SucursalTexto56;
    private javax.swing.JLabel jLabel1SucursalTexto58;
    private javax.swing.JLabel jLabel1SucursalTexto59;
    private javax.swing.JLabel jLabel1SucursalTexto61;
    private javax.swing.JLabel jLabel1SucursalTexto62;
    private javax.swing.JLabel jLabel1SucursalTexto63;
    private javax.swing.JLabel jLabel1SucursalTexto64;
    private javax.swing.JLabel jLabel1SucursalTexto65;
    private javax.swing.JLabel jLabel1SucursalTexto66;
    private javax.swing.JLabel jLabel1SucursalTexto67;
    private javax.swing.JLabel jLabel1SucursalTexto68;
    private javax.swing.JLabel jLabel1SucursalTexto69;
    private javax.swing.JLabel jLabel1SucursalTexto70;
    private javax.swing.JLabel jLabel1SucursalTexto71;
    private javax.swing.JLabel jLabel1SucursalTexto72;
    private javax.swing.JLabel jLabel1SucursalTexto73;
    private javax.swing.JLabel jLabel1SucursalTexto74;
    private javax.swing.JLabel jLabel1SucursalTexto75;
    private javax.swing.JLabel jLabel1SucursalTexto76;
    private javax.swing.JLabel jLabel1SucursalTexto77;
    private javax.swing.JLabel jLabel1SucursalTexto78;
    private javax.swing.JLabel jLabel1SucursalTexto79;
    private javax.swing.JLabel jLabel1SucursalTexto80;
    private javax.swing.JLabel jLabel1SucursalTexto81;
    private javax.swing.JLabel jLabel1SucursalTexto82;
    private javax.swing.JLabel jLabel1SucursalTexto83;
    private javax.swing.JLabel jLabel1SucursalTexto84;
    private javax.swing.JLabel jLabel1SucursalTexto85;
    private javax.swing.JLabel jLabel1SucursalTexto86;
    private javax.swing.JLabel jLabel1SucursalTexto87;
    private javax.swing.JLabel jLabel1SucursalTexto88;
    private javax.swing.JLabel jLabel1SucursalTexto89;
    private javax.swing.JLabel jLabel1Usuario2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel2Contraseña1;
    private javax.swing.JLabel jLabel2Contraseña12;
    private javax.swing.JLabel jLabel2Contraseña22;
    private javax.swing.JLabel jLabel2Contraseña23;
    private javax.swing.JLabel jLabel2Contraseña24;
    private javax.swing.JLabel jLabel2Contraseña25;
    private javax.swing.JLabel jLabel2Contraseña26;
    private javax.swing.JLabel jLabel2Contraseña27;
    private javax.swing.JLabel jLabel2Contraseña28;
    private javax.swing.JLabel jLabel2Contraseña29;
    private javax.swing.JLabel jLabel2Contraseña3;
    private javax.swing.JLabel jLabel2Contraseña30;
    private javax.swing.JLabel jLabel2Contraseña31;
    private javax.swing.JLabel jLabel2Contraseña32;
    private javax.swing.JLabel jLabel2Contraseña33;
    private javax.swing.JLabel jLabel2Contraseña34;
    private javax.swing.JLabel jLabel2Contraseña35;
    private javax.swing.JLabel jLabel2Contraseña8;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel1MenuTelefono;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel2Central2;
    private javax.swing.JPanel jPanel2Lateral1;
    private javax.swing.JPanel jPanel2Lateral1Inferior3;
    private javax.swing.JPanel jPanel2Superior3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
