/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.Color;

/**
 *
 * @author Hp
 */
public class Colegas extends javax.swing.JFrame {

    /**
     * Creates new form Colegas
     */
    public Colegas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenido = new javax.swing.JPanel();
        jPanelNuevoCompi = new javax.swing.JPanel();
        jLabelTextoNuevoCompis = new javax.swing.JLabel();
        jLabelTextoApellido = new javax.swing.JLabel();
        jLabelTextoTelefono = new javax.swing.JLabel();
        jLabelTextoOcupacion = new javax.swing.JLabel();
        jLabelTextoPerfil = new javax.swing.JLabel();
        jLabelTextoNombre = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldOcupacion = new javax.swing.JTextField();
        jTextFieldPefil = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jButtonAgendar = new javax.swing.JButton();
        jPanelDatos = new javax.swing.JPanel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelOcupacion = new javax.swing.JLabel();
        jLabelPerfil = new javax.swing.JLabel();
        jLabelTextoNombreApellido = new javax.swing.JLabel();
        jLabelNombre2 = new javax.swing.JLabel();
        jLabelNombre3 = new javax.swing.JLabel();
        jLabelTelefono3 = new javax.swing.JLabel();
        jLabelNombre1 = new javax.swing.JLabel();
        jLabelOcupacion3 = new javax.swing.JLabel();
        jLabelTelefono2 = new javax.swing.JLabel();
        jLabelTelefono1 = new javax.swing.JLabel();
        jLabelPerfil3 = new javax.swing.JLabel();
        jLabelOcupacion2 = new javax.swing.JLabel();
        jLabelOcupacion1 = new javax.swing.JLabel();
        jLabelPefil1 = new javax.swing.JLabel();
        jLabelPerfil2 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelIconoGitHub = new javax.swing.JLabel();
        jLabelIconoInstagram = new javax.swing.JLabel();
        jLabelIconoLinkedin = new javax.swing.JLabel();
        panelMenuLateral = new javax.swing.JPanel();
        jLabelTextoBrothers = new javax.swing.JLabel();
        jLabelLogoImagen = new javax.swing.JLabel();
        jButtonMiMusica = new javax.swing.JButton();
        jButtonColegas = new javax.swing.JButton();
        jButtonIdeas = new javax.swing.JButton();
        jButtonApuntes = new javax.swing.JButton();
        jButtonTutoriales = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelContenido.setBackground(new java.awt.Color(35, 35, 35));
        panelContenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNuevoCompi.setBackground(new java.awt.Color(0, 0, 0));
        jPanelNuevoCompi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(137, 0, 137)));
        jPanelNuevoCompi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextoNuevoCompis.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabelTextoNuevoCompis.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoNuevoCompis.setText("Nuevo Compis");
        jPanelNuevoCompi.add(jLabelTextoNuevoCompis, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        jLabelTextoApellido.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabelTextoApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoApellido.setText("Apellido:");
        jPanelNuevoCompi.add(jLabelTextoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabelTextoTelefono.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabelTextoTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoTelefono.setText("Telefono:");
        jPanelNuevoCompi.add(jLabelTextoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabelTextoOcupacion.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabelTextoOcupacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoOcupacion.setText("Ocupacion:");
        jPanelNuevoCompi.add(jLabelTextoOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jLabelTextoPerfil.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabelTextoPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoPerfil.setText("Perfil:");
        jPanelNuevoCompi.add(jLabelTextoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabelTextoNombre.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabelTextoNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoNombre.setText("Nombre:");
        jPanelNuevoCompi.add(jLabelTextoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jTextFieldApellido.setBackground(new java.awt.Color(35, 35, 35));
        jTextFieldApellido.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelNuevoCompi.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 110, 20));

        jTextFieldTelefono.setBackground(new java.awt.Color(35, 35, 35));
        jTextFieldTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });
        jPanelNuevoCompi.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 110, 20));

        jTextFieldOcupacion.setBackground(new java.awt.Color(35, 35, 35));
        jTextFieldOcupacion.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldOcupacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelNuevoCompi.add(jTextFieldOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 110, 20));

        jTextFieldPefil.setBackground(new java.awt.Color(35, 35, 35));
        jTextFieldPefil.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldPefil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelNuevoCompi.add(jTextFieldPefil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 110, 20));

        jTextFieldNombre.setBackground(new java.awt.Color(35, 35, 35));
        jTextFieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelNuevoCompi.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 110, 20));

        jButtonAgendar.setBackground(new java.awt.Color(25, 207, 196));
        jButtonAgendar.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jButtonAgendar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAgendar.setText("AGENDAR");
        jButtonAgendar.setBorder(null);
        jButtonAgendar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAgendarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAgendarMouseExited(evt);
            }
        });
        jPanelNuevoCompi.add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 130, 40));

        panelContenido.add(jPanelNuevoCompi, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 310, 420));

        jPanelDatos.setBackground(new java.awt.Color(0, 0, 0));
        jPanelDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 108)));
        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTelefono.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono.setText("Telefono");
        jPanelDatos.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        jLabelOcupacion.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabelOcupacion.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOcupacion.setText("Ocupacion");
        jPanelDatos.add(jLabelOcupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabelPerfil.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabelPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfil.setText("Perfil");
        jPanelDatos.add(jLabelPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));

        jLabelTextoNombreApellido.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabelTextoNombreApellido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoNombreApellido.setText("Nombre y Apellido");
        jPanelDatos.add(jLabelTextoNombreApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabelNombre2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre2.setText("Julia Cortez");
        jPanelDatos.add(jLabelNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jLabelNombre3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre3.setText("Laura Rodriguez");
        jPanelDatos.add(jLabelNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabelTelefono3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono3.setText("644718598");
        jPanelDatos.add(jLabelTelefono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, -1, -1));

        jLabelNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre1.setText("Juan Carlos Lucero");
        jPanelDatos.add(jLabelNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabelOcupacion3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOcupacion3.setText("Freelance");
        jPanelDatos.add(jLabelOcupacion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jLabelTelefono2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono2.setText("655258741");
        jPanelDatos.add(jLabelTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, -1));

        jLabelTelefono1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTelefono1.setText("642547863");
        jPanelDatos.add(jLabelTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        jLabelPerfil3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfil3.setText("Diseñadora");
        jPanelDatos.add(jLabelPerfil3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, -1));

        jLabelOcupacion2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOcupacion2.setText("Freelance");
        jPanelDatos.add(jLabelOcupacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        jLabelOcupacion1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOcupacion1.setText("Empresa DIGITEC");
        jPanelDatos.add(jLabelOcupacion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, -1));

        jLabelPefil1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPefil1.setText("Front-End");
        jPanelDatos.add(jLabelPefil1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabelPerfil2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerfil2.setText("Full Stack");
        jPanelDatos.add(jLabelPerfil2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        panelContenido.add(jPanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 480, 420));

        jLabelTitulo.setFont(new java.awt.Font("Poppins", 0, 48)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Colegas");
        panelContenido.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabelIconoGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/github30.png"))); // NOI18N
        jLabelIconoGitHub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoGitHubMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoGitHubMouseExited(evt);
            }
        });
        panelContenido.add(jLabelIconoGitHub, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 610, -1, -1));

        jLabelIconoInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/instagram30.png"))); // NOI18N
        jLabelIconoInstagram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoInstagramMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoInstagramMouseExited(evt);
            }
        });
        panelContenido.add(jLabelIconoInstagram, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 610, -1, -1));

        jLabelIconoLinkedin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/linkedin30.png"))); // NOI18N
        jLabelIconoLinkedin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelIconoLinkedinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelIconoLinkedinMouseExited(evt);
            }
        });
        panelContenido.add(jLabelIconoLinkedin, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 610, -1, -1));

        getContentPane().add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1010, 670));

        panelMenuLateral.setBackground(new java.awt.Color(0, 0, 0));
        panelMenuLateral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTextoBrothers.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        jLabelTextoBrothers.setForeground(new java.awt.Color(255, 0, 153));
        jLabelTextoBrothers.setText("Brothers");
        panelMenuLateral.add(jLabelTextoBrothers, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        jLabelLogoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logo.png"))); // NOI18N
        panelMenuLateral.add(jLabelLogoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jButtonMiMusica.setBackground(new java.awt.Color(35, 35, 35));
        jButtonMiMusica.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButtonMiMusica.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMiMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/auriculares.png"))); // NOI18N
        jButtonMiMusica.setText("Mi Musica");
        jButtonMiMusica.setBorder(null);
        jButtonMiMusica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMiMusicaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMiMusicaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMiMusicaMouseExited(evt);
            }
        });
        panelMenuLateral.add(jButtonMiMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 200, 50));

        jButtonColegas.setBackground(new java.awt.Color(255, 0, 153));
        jButtonColegas.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButtonColegas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonColegas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/colegas.png"))); // NOI18N
        jButtonColegas.setText("Colegas");
        jButtonColegas.setBorder(null);
        panelMenuLateral.add(jButtonColegas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 200, 50));

        jButtonIdeas.setBackground(new java.awt.Color(35, 35, 35));
        jButtonIdeas.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButtonIdeas.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIdeas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bombilla.png"))); // NOI18N
        jButtonIdeas.setText("Ideas");
        jButtonIdeas.setBorder(null);
        jButtonIdeas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIdeasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonIdeasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonIdeasMouseExited(evt);
            }
        });
        panelMenuLateral.add(jButtonIdeas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 200, 50));

        jButtonApuntes.setBackground(new java.awt.Color(35, 35, 35));
        jButtonApuntes.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButtonApuntes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonApuntes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/apuntes-de-clase.png"))); // NOI18N
        jButtonApuntes.setText("Apuntes");
        jButtonApuntes.setBorder(null);
        jButtonApuntes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonApuntesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonApuntesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonApuntesMouseExited(evt);
            }
        });
        panelMenuLateral.add(jButtonApuntes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 200, 50));

        jButtonTutoriales.setBackground(new java.awt.Color(35, 35, 35));
        jButtonTutoriales.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jButtonTutoriales.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTutoriales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/video.png"))); // NOI18N
        jButtonTutoriales.setText("Tutoriales");
        jButtonTutoriales.setBorder(null);
        jButtonTutoriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTutorialesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTutorialesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTutorialesMouseExited(evt);
            }
        });
        panelMenuLateral.add(jButtonTutoriales, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 200, 50));

        jButtonSalir.setBackground(new java.awt.Color(25, 207, 196));
        jButtonSalir.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(0, 0, 0));
        jButtonSalir.setText("SALIR");
        jButtonSalir.setBorder(null);
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
        });
        panelMenuLateral.add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 130, 40));

        getContentPane().add(panelMenuLateral, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jButtonApuntesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonApuntesMouseClicked
    Apuntes abrir = new Apuntes();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);        }//GEN-LAST:event_jButtonApuntesMouseClicked

    private void jButtonMiMusicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMiMusicaMouseClicked
        MiMusica abrir = new MiMusica();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jButtonMiMusicaMouseClicked

    private void jButtonIdeasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIdeasMouseClicked
        Ideas abrir = new Ideas();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);    }//GEN-LAST:event_jButtonIdeasMouseClicked

    private void jButtonTutorialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTutorialesMouseClicked
        Tutoriales abrir = new Tutoriales();
        abrir.setVisible(true);
        abrir.setLocationRelativeTo(null);
        this.setVisible(false);     }//GEN-LAST:event_jButtonTutorialesMouseClicked

    private void jButtonApuntesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonApuntesMouseExited
        jButtonApuntes.setBackground(new Color(35, 35, 35)); //Provide the r g b values

    }//GEN-LAST:event_jButtonApuntesMouseExited

    private void jButtonApuntesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonApuntesMouseEntered
        jButtonApuntes.setBackground(new Color(255, 0, 153)); //Provide the r g b values

    }//GEN-LAST:event_jButtonApuntesMouseEntered

    private void jButtonMiMusicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMiMusicaMouseEntered
           jButtonMiMusica.setBackground(new Color(255, 0, 153)); //Provide the r g b values
    }//GEN-LAST:event_jButtonMiMusicaMouseEntered

    private void jButtonMiMusicaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMiMusicaMouseExited
        jButtonMiMusica.setBackground(new Color(35, 35, 35)); //Provide the r g b values
    }//GEN-LAST:event_jButtonMiMusicaMouseExited

    private void jButtonIdeasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIdeasMouseEntered
        jButtonIdeas.setBackground(new Color(255, 0, 153)); //Provide the r g b values
    }//GEN-LAST:event_jButtonIdeasMouseEntered

    private void jButtonIdeasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIdeasMouseExited
        jButtonIdeas.setBackground(new Color(35, 35, 35)); //Provide the r g b values
    }//GEN-LAST:event_jButtonIdeasMouseExited

    private void jButtonTutorialesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTutorialesMouseEntered
        jButtonTutoriales.setBackground(new Color(255, 0, 153)); //Provide the r g b values
    }//GEN-LAST:event_jButtonTutorialesMouseEntered

    private void jButtonTutorialesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTutorialesMouseExited
        jButtonTutoriales.setBackground(new Color(35, 35, 35)); //Provide the r g b values
    }//GEN-LAST:event_jButtonTutorialesMouseExited

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
        System.exit(0);

    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        jButtonSalir.setBackground(new Color(19,130,124)); //Provide the r g b values
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        jButtonSalir.setBackground(new Color(25,207,196)); //Provide the r g b values
    }//GEN-LAST:event_jButtonSalirMouseExited

    private void jButtonAgendarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgendarMouseEntered
        jButtonAgendar.setBackground(new Color(19,130,124)); //Provide the r g b values
    }//GEN-LAST:event_jButtonAgendarMouseEntered

    private void jButtonAgendarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAgendarMouseExited
        jButtonAgendar.setBackground(new Color(25,207,196)); //Provide the r g b values

    }//GEN-LAST:event_jButtonAgendarMouseExited

    private void jLabelIconoLinkedinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoLinkedinMouseEntered
jLabelIconoLinkedin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/linkedinrosa30.png")));

    }//GEN-LAST:event_jLabelIconoLinkedinMouseEntered

    private void jLabelIconoLinkedinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoLinkedinMouseExited
jLabelIconoLinkedin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/linkedin30.png")));
    }//GEN-LAST:event_jLabelIconoLinkedinMouseExited

    private void jLabelIconoGitHubMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoGitHubMouseEntered
jLabelIconoGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/githubrosa30.png")));
    }//GEN-LAST:event_jLabelIconoGitHubMouseEntered

    private void jLabelIconoGitHubMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoGitHubMouseExited
jLabelIconoGitHub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/github30.png")));
    }//GEN-LAST:event_jLabelIconoGitHubMouseExited

    private void jLabelIconoInstagramMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInstagramMouseEntered
jLabelIconoInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/instagramrosa30.png")));
    }//GEN-LAST:event_jLabelIconoInstagramMouseEntered

    private void jLabelIconoInstagramMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelIconoInstagramMouseExited
jLabelIconoInstagram.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/instagram30.png")));
    }//GEN-LAST:event_jLabelIconoInstagramMouseExited

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Colegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Colegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Colegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Colegas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Colegas().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JButton jButtonApuntes;
    private javax.swing.JButton jButtonColegas;
    private javax.swing.JButton jButtonIdeas;
    private javax.swing.JButton jButtonMiMusica;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonTutoriales;
    private javax.swing.JLabel jLabelIconoGitHub;
    private javax.swing.JLabel jLabelIconoInstagram;
    private javax.swing.JLabel jLabelIconoLinkedin;
    private javax.swing.JLabel jLabelLogoImagen;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JLabel jLabelOcupacion;
    private javax.swing.JLabel jLabelOcupacion1;
    private javax.swing.JLabel jLabelOcupacion2;
    private javax.swing.JLabel jLabelOcupacion3;
    private javax.swing.JLabel jLabelPefil1;
    private javax.swing.JLabel jLabelPerfil;
    private javax.swing.JLabel jLabelPerfil2;
    private javax.swing.JLabel jLabelPerfil3;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefono1;
    private javax.swing.JLabel jLabelTelefono2;
    private javax.swing.JLabel jLabelTelefono3;
    private javax.swing.JLabel jLabelTextoApellido;
    private javax.swing.JLabel jLabelTextoBrothers;
    private javax.swing.JLabel jLabelTextoNombre;
    private javax.swing.JLabel jLabelTextoNombreApellido;
    private javax.swing.JLabel jLabelTextoNuevoCompis;
    private javax.swing.JLabel jLabelTextoOcupacion;
    private javax.swing.JLabel jLabelTextoPerfil;
    private javax.swing.JLabel jLabelTextoTelefono;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelNuevoCompi;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldOcupacion;
    private javax.swing.JTextField jTextFieldPefil;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelMenuLateral;
    // End of variables declaration//GEN-END:variables
}
